version: 2

updates:
  - package-ecosystem: cargo
    directories:
      - /client
      - /host
    schedule:
      interval: daily
    groups:
      crates-io:
        patterns:
          - "*"

  - package-ecosystem: rust-toolchain
    directories:
      - /.github
    schedule:
      interval: daily
    groups:
      rust:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directories:
      - /host/ld/src/js
      - /host/runner/src/js
    schedule:
      interval: daily
    groups:
      npm:
        patterns:
          - "*"
