//! This file was generated by `js-sys-bindgen`.
#![allow(warnings)]
use core::ops::Deref;
use crate::JsValue;
use crate::hazard::{Input, Output};
#[repr(transparent)]
pub struct JsBigInt(JsValue);
impl Deref for JsBigInt {
    type Target = JsValue;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<JsBigInt> for JsValue {
    fn from(value: JsBigInt) -> Self {
        value.0
    }
}
unsafe impl Input for &JsBigInt {
    const ASM_IMPORT_FUNC: Option<&'static str> = <&JsValue as Input>::ASM_IMPORT_FUNC;
    const ASM_IMPORT_TYPE: &'static str = <&JsValue as Input>::ASM_IMPORT_TYPE;
    const ASM_TYPE: &'static str = <&JsValue as Input>::ASM_TYPE;
    const ASM_CONV: Option<&'static str> = <&JsValue as Input>::ASM_CONV;
    type Type = <&'static JsValue as Input>::Type;
    fn into_raw(self) -> Self::Type {
        Input::into_raw(&self.0)
    }
}
unsafe impl Output for JsBigInt {
    const ASM_IMPORT_FUNC: Option<&str> = <JsValue as Output>::ASM_IMPORT_FUNC;
    const ASM_IMPORT_TYPE: &str = <JsValue as Output>::ASM_IMPORT_TYPE;
    const ASM_TYPE: &str = <JsValue as Output>::ASM_TYPE;
    const ASM_CONV: Option<&str> = <JsValue as Output>::ASM_CONV;
    type Type = <JsValue as Output>::Type;
    fn from_raw(raw: Self::Type) -> Self {
        Self(Output::from_raw(raw))
    }
}
impl JsBigInt {
    #[must_use]
    pub fn unchecked_from(value: JsValue) -> Self {
        Self(value)
    }
}
