//! This file was generated by `js-sys-bindgen`.

#![allow(warnings)]

use core::marker::PhantomData;
use core::ops::Deref;
use crate::{js_bindgen, r#macro, JsValue};
use crate::hazard::{Input, InputJsConv, InputAsmConv, OutputAsmConv, Output, OutputJsConv};
use crate::util::PtrLength;

#[repr(transparent)]
pub struct JsArray<T = JsValue> {
	value: JsValue,
	_type: PhantomData<T>,
}

impl<T> Deref for JsArray<T> {
	type Target = JsValue;

	fn deref(&self) -> &Self::Target {
		&self.value
	}
}

impl<T> From<JsArray<T>> for JsValue {
	fn from(value: JsArray<T>) -> Self {
		value.value
	}
}

unsafe impl<T> Input for &JsArray<T> {
	const ASM_TYPE: &'static str = <&JsValue as Input>::ASM_TYPE;
	const ASM_CONV: Option<InputAsmConv> = <&JsValue as Input>::ASM_CONV;
	const JS_CONV: Option<InputJsConv> = <&JsValue as Input>::JS_CONV;

	type Type = <&'static JsValue as Input>::Type;

	fn into_raw(self) -> Self::Type {
		Input::into_raw(&self.value)
	}
}

unsafe impl<T> Output for JsArray<T> {
	const ASM_TYPE: &str = <JsValue as Output>::ASM_TYPE;
	const ASM_CONV: Option<OutputAsmConv> = <JsValue as Output>::ASM_CONV;
	const JS_CONV: Option<OutputJsConv> = <JsValue as Output>::JS_CONV;

	type Type = <JsValue as Output>::Type;

	fn from_raw(raw: Self::Type) -> Self {
		Self {
			value: Output::from_raw(raw),
			_type: PhantomData,
		}
	}
}

impl<T> JsArray<T> {
	#[must_use]
	pub fn unchecked_from(value: JsValue) -> Self {
		Self { value, _type: PhantomData }
	}
}

impl<T> JsArray<T> {
	pub fn length(self: &JsArray<T>) -> u32 {
		js_bindgen::unsafe_embed_asm! {
			"(import \"js_sys\" \"length\" (func $js_sys.import.length (@sym (name \"js_sys.import.length\")) (param {}) (result {})))",
			"{}",
			"",
			"{}",
			"",
			"(func $js_sys.length (@sym) (param {} {}) (result {})",
			"  local.get {}",
			"  call $js_sys.import.length (@reloc)",
			"{}",
			")",
			interpolate r#macro::asm_input_import_type::<&JsValue>(),
			interpolate r#macro::asm_output_import_type::<u32>(),
			interpolate r#macro::asm_input_import::<&JsValue>(),
			interpolate r#macro::asm_output_import::<u32>(),
			interpolate r#macro::asm_indirect!(u32),
			interpolate <&JsValue as Input>::ASM_TYPE,
			interpolate r#macro::asm_direct::<u32>(),
			interpolate r#macro::asm_input!("0", "1", &JsValue, u32),
			interpolate r#macro::asm_output!(u32),
		}

		js_bindgen::import_js! {
			module = "js_sys",
			name = "length",
			required_embeds = [
				r#macro::js_input_embed::<&JsValue>(),
				r#macro::js_output_embed::<u32>(),
			],
			"{}{}{}",
			interpolate r#macro::js_select!("(self) => ", "(self) => {\n", (&JsValue), u32),
			interpolate r#macro::js_parameter!("self", &JsValue),
			interpolate r#macro::js_output!(
				"\treturn ",
				"self.length",
				"self.length",
				u32,
				&JsValue,
			),
		}

		unsafe extern "C" {
			#[link_name = "js_sys.length"]
			fn length(this: <&JsValue as Input>::Type) -> <u32 as Output>::Type;
		}

		Output::from_raw(unsafe { length(Input::into_raw(self)) })
	}
}

pub(super) unsafe fn array_js_value_decode(
	array: *const JsValue,
	len: PtrLength<JsValue>,
) -> JsArray<JsValue> {
	js_bindgen::unsafe_embed_asm! {
		"(import \"js_sys\" \"array_js_value_decode\" (func $js_sys.import.array_js_value_decode (@sym (name \"js_sys.import.array_js_value_decode\")) (param {} {}) (result {})))",
		"{}",
		"",
		"{}",
		"",
		"{}",
		"",
		"(func $js_sys.array_js_value_decode (@sym) (param {} {} {}) (result {})",
		"  local.get {}",
		"  local.get {}",
		"  call $js_sys.import.array_js_value_decode (@reloc)",
		"{}",
		")",
		interpolate r#macro::asm_input_import_type::<*const JsValue>(),
		interpolate r#macro::asm_input_import_type::<PtrLength<JsValue>>(),
		interpolate r#macro::asm_output_import_type::<JsArray<JsValue>>(),
		interpolate r#macro::asm_input_import::<*const JsValue>(),
		interpolate r#macro::asm_input_import::<PtrLength<JsValue>>(),
		interpolate r#macro::asm_output_import::<JsArray<JsValue>>(),
		interpolate r#macro::asm_indirect!(JsArray<JsValue>),
		interpolate <*const JsValue as Input>::ASM_TYPE,
		interpolate <PtrLength<JsValue> as Input>::ASM_TYPE,
		interpolate r#macro::asm_direct::<JsArray<JsValue>>(),
		interpolate r#macro::asm_input!("0", "1", *const JsValue, JsArray<JsValue>),
		interpolate r#macro::asm_input!("1", "2", PtrLength<JsValue>, JsArray<JsValue>),
		interpolate r#macro::asm_output!(JsArray<JsValue>),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "array_js_value_decode",
		required_embeds = [
			("js_sys", "array.js_value.decode"),
			r#macro::js_input_embed::<*const JsValue>(),
			r#macro::js_input_embed::<PtrLength<JsValue>>(),
			r#macro::js_output_embed::<JsArray<JsValue>>(),
		],
		"{}{}{}{}",
		interpolate r#macro::js_select!(
			"",
			"(array, len) => {\n",
			(*const JsValue, PtrLength<JsValue>),
			JsArray<JsValue>,
		),
		interpolate r#macro::js_parameter!("array", *const JsValue),
		interpolate r#macro::js_parameter!("len", PtrLength<JsValue>),
		interpolate r#macro::js_output!(
			"\treturn ",
			"this.#jsEmbed.js_sys['array.js_value.decode']",
			"this.#jsEmbed.js_sys['array.js_value.decode'](array, len)",
			JsArray<JsValue>,
			*const JsValue,
			PtrLength<JsValue>,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.array_js_value_decode"]
		fn array_js_value_decode(
			array: <*const JsValue as Input>::Type,
			len: <PtrLength<JsValue> as Input>::Type,
		) -> <JsArray<JsValue> as Output>::Type;
	}

	Output::from_raw(unsafe { array_js_value_decode(Input::into_raw(array), Input::into_raw(len)) })
}

pub(super) unsafe fn array_js_value_encode(
	array: &JsArray,
	array_ptr: *mut JsValue,
	array_len: PtrLength<JsValue>,
	externref_ptr: *const i32,
	externref_len: i32,
) -> bool {
	js_bindgen::unsafe_embed_asm! {
		"(import \"js_sys\" \"array_js_value_encode\" (func $js_sys.import.array_js_value_encode (@sym (name \"js_sys.import.array_js_value_encode\")) (param {} {} {} {} {}) (result {})))",
		"{}",
		"",
		"{}",
		"",
		"{}",
		"",
		"{}",
		"",
		"{}",
		"",
		"{}",
		"",
		"(func $js_sys.array_js_value_encode (@sym) (param {} {} {} {} {} {}) (result {})",
		"  local.get {}",
		"  local.get {}",
		"  local.get {}",
		"  local.get {}",
		"  local.get {}",
		"  call $js_sys.import.array_js_value_encode (@reloc)",
		"{}",
		")",
		interpolate r#macro::asm_input_import_type::<&JsArray>(),
		interpolate r#macro::asm_input_import_type::<*mut JsValue>(),
		interpolate r#macro::asm_input_import_type::<PtrLength<JsValue>>(),
		interpolate r#macro::asm_input_import_type::<*const i32>(),
		interpolate r#macro::asm_input_import_type::<i32>(),
		interpolate r#macro::asm_output_import_type::<bool>(),
		interpolate r#macro::asm_input_import::<&JsArray>(),
		interpolate r#macro::asm_input_import::<*mut JsValue>(),
		interpolate r#macro::asm_input_import::<PtrLength<JsValue>>(),
		interpolate r#macro::asm_input_import::<*const i32>(),
		interpolate r#macro::asm_input_import::<i32>(),
		interpolate r#macro::asm_output_import::<bool>(),
		interpolate r#macro::asm_indirect!(bool),
		interpolate <&JsArray as Input>::ASM_TYPE,
		interpolate <*mut JsValue as Input>::ASM_TYPE,
		interpolate <PtrLength<JsValue> as Input>::ASM_TYPE,
		interpolate <*const i32 as Input>::ASM_TYPE,
		interpolate <i32 as Input>::ASM_TYPE,
		interpolate r#macro::asm_direct::<bool>(),
		interpolate r#macro::asm_input!("0", "1", &JsArray, bool),
		interpolate r#macro::asm_input!("1", "2", *mut JsValue, bool),
		interpolate r#macro::asm_input!("2", "3", PtrLength<JsValue>, bool),
		interpolate r#macro::asm_input!("3", "4", *const i32, bool),
		interpolate r#macro::asm_input!("4", "5", i32, bool),
		interpolate r#macro::asm_output!(bool),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "array_js_value_encode",
		required_embeds = [
			("js_sys", "array.js_value.encode"),
			r#macro::js_input_embed::<&JsArray>(),
			r#macro::js_input_embed::<*mut JsValue>(),
			r#macro::js_input_embed::<PtrLength<JsValue>>(),
			r#macro::js_input_embed::<*const i32>(),
			r#macro::js_input_embed::<i32>(),
			r#macro::js_output_embed::<bool>(),
		],
		"{}{}{}{}{}{}{}",
		interpolate r#macro::js_select!(
			"",
			"(array, array_ptr, array_len, externref_ptr, externref_len) => {\n",
			(&JsArray, *mut JsValue, PtrLength<JsValue>, *const i32, i32),
			bool,
		),
		interpolate r#macro::js_parameter!("array", &JsArray),
		interpolate r#macro::js_parameter!("array_ptr", *mut JsValue),
		interpolate r#macro::js_parameter!("array_len", PtrLength<JsValue>),
		interpolate r#macro::js_parameter!("externref_ptr", *const i32),
		interpolate r#macro::js_parameter!("externref_len", i32),
		interpolate r#macro::js_output!(
			"\treturn ",
			"this.#jsEmbed.js_sys['array.js_value.encode']",
			"this.#jsEmbed.js_sys['array.js_value.encode'](array, array_ptr, array_len, externref_ptr, externref_len)",
			bool,
			&JsArray,
			*mut JsValue,
			PtrLength<JsValue>,
			*const i32,
			i32,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.array_js_value_encode"]
		fn array_js_value_encode(
			array: <&JsArray as Input>::Type,
			array_ptr: <*mut JsValue as Input>::Type,
			array_len: <PtrLength<JsValue> as Input>::Type,
			externref_ptr: <*const i32 as Input>::Type,
			externref_len: <i32 as Input>::Type,
		) -> <bool as Output>::Type;
	}

	Output::from_raw(unsafe {
		array_js_value_encode(
			Input::into_raw(array),
			Input::into_raw(array_ptr),
			Input::into_raw(array_len),
			Input::into_raw(externref_ptr),
			Input::into_raw(externref_len),
		)
	})
}

pub(super) unsafe fn array_u32_decode(array: *const u32, len: PtrLength<u32>) -> JsArray<u32> {
	js_bindgen::unsafe_embed_asm! {
		"(import \"js_sys\" \"array_u32_decode\" (func $js_sys.import.array_u32_decode (@sym (name \"js_sys.import.array_u32_decode\")) (param {} {}) (result {})))",
		"{}",
		"",
		"{}",
		"",
		"{}",
		"",
		"(func $js_sys.array_u32_decode (@sym) (param {} {} {}) (result {})",
		"  local.get {}",
		"  local.get {}",
		"  call $js_sys.import.array_u32_decode (@reloc)",
		"{}",
		")",
		interpolate r#macro::asm_input_import_type::<*const u32>(),
		interpolate r#macro::asm_input_import_type::<PtrLength<u32>>(),
		interpolate r#macro::asm_output_import_type::<JsArray<u32>>(),
		interpolate r#macro::asm_input_import::<*const u32>(),
		interpolate r#macro::asm_input_import::<PtrLength<u32>>(),
		interpolate r#macro::asm_output_import::<JsArray<u32>>(),
		interpolate r#macro::asm_indirect!(JsArray<u32>),
		interpolate <*const u32 as Input>::ASM_TYPE,
		interpolate <PtrLength<u32> as Input>::ASM_TYPE,
		interpolate r#macro::asm_direct::<JsArray<u32>>(),
		interpolate r#macro::asm_input!("0", "1", *const u32, JsArray<u32>),
		interpolate r#macro::asm_input!("1", "2", PtrLength<u32>, JsArray<u32>),
		interpolate r#macro::asm_output!(JsArray<u32>),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "array_u32_decode",
		required_embeds = [
			("js_sys", "view.getUint32"),
			r#macro::js_input_embed::<*const u32>(),
			r#macro::js_input_embed::<PtrLength<u32>>(),
			r#macro::js_output_embed::<JsArray<u32>>(),
		],
		"{}{}{}{}",
		interpolate r#macro::js_select!(
			"",
			"(array, len) => {\n",
			(*const u32, PtrLength<u32>),
			JsArray<u32>,
		),
		interpolate r#macro::js_parameter!("array", *const u32),
		interpolate r#macro::js_parameter!("len", PtrLength<u32>),
		interpolate r#macro::js_output!(
			"\treturn ",
			"this.#jsEmbed.js_sys['view.getUint32']",
			"this.#jsEmbed.js_sys['view.getUint32'](array, len)",
			JsArray<u32>,
			*const u32,
			PtrLength<u32>,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.array_u32_decode"]
		fn array_u32_decode(
			array: <*const u32 as Input>::Type,
			len: <PtrLength<u32> as Input>::Type,
		) -> <JsArray<u32> as Output>::Type;
	}

	Output::from_raw(unsafe { array_u32_decode(Input::into_raw(array), Input::into_raw(len)) })
}

pub(super) unsafe fn array_u32_encode(
	array: &JsArray<u32>,
	ptr: *mut u32,
	len: PtrLength<u32>,
) -> bool {
	js_bindgen::unsafe_embed_asm! {
		"(import \"js_sys\" \"array_u32_encode\" (func $js_sys.import.array_u32_encode (@sym (name \"js_sys.import.array_u32_encode\")) (param {} {} {}) (result {})))",
		"{}",
		"",
		"{}",
		"",
		"{}",
		"",
		"{}",
		"",
		"(func $js_sys.array_u32_encode (@sym) (param {} {} {} {}) (result {})",
		"  local.get {}",
		"  local.get {}",
		"  local.get {}",
		"  call $js_sys.import.array_u32_encode (@reloc)",
		"{}",
		")",
		interpolate r#macro::asm_input_import_type::<&JsArray<u32>>(),
		interpolate r#macro::asm_input_import_type::<*mut u32>(),
		interpolate r#macro::asm_input_import_type::<PtrLength<u32>>(),
		interpolate r#macro::asm_output_import_type::<bool>(),
		interpolate r#macro::asm_input_import::<&JsArray<u32>>(),
		interpolate r#macro::asm_input_import::<*mut u32>(),
		interpolate r#macro::asm_input_import::<PtrLength<u32>>(),
		interpolate r#macro::asm_output_import::<bool>(),
		interpolate r#macro::asm_indirect!(bool),
		interpolate <&JsArray<u32> as Input>::ASM_TYPE,
		interpolate <*mut u32 as Input>::ASM_TYPE,
		interpolate <PtrLength<u32> as Input>::ASM_TYPE,
		interpolate r#macro::asm_direct::<bool>(),
		interpolate r#macro::asm_input!("0", "1", &JsArray<u32>, bool),
		interpolate r#macro::asm_input!("1", "2", *mut u32, bool),
		interpolate r#macro::asm_input!("2", "3", PtrLength<u32>, bool),
		interpolate r#macro::asm_output!(bool),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "array_u32_encode",
		required_embeds = [
			("js_sys", "array.u32.encode"),
			r#macro::js_input_embed::<&JsArray<u32>>(),
			r#macro::js_input_embed::<*mut u32>(),
			r#macro::js_input_embed::<PtrLength<u32>>(),
			r#macro::js_output_embed::<bool>(),
		],
		"{}{}{}{}{}",
		interpolate r#macro::js_select!(
			"",
			"(array, ptr, len) => {\n",
			(&JsArray<u32>, *mut u32, PtrLength<u32>),
			bool,
		),
		interpolate r#macro::js_parameter!("array", &JsArray<u32>),
		interpolate r#macro::js_parameter!("ptr", *mut u32),
		interpolate r#macro::js_parameter!("len", PtrLength<u32>),
		interpolate r#macro::js_output!(
			"\treturn ",
			"this.#jsEmbed.js_sys['array.u32.encode']",
			"this.#jsEmbed.js_sys['array.u32.encode'](array, ptr, len)",
			bool,
			&JsArray<u32>,
			*mut u32,
			PtrLength<u32>,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.array_u32_encode"]
		fn array_u32_encode(
			array: <&JsArray<u32> as Input>::Type,
			ptr: <*mut u32 as Input>::Type,
			len: <PtrLength<u32> as Input>::Type,
		) -> <bool as Output>::Type;
	}

	Output::from_raw(unsafe {
		array_u32_encode(Input::into_raw(array), Input::into_raw(ptr), Input::into_raw(len))
	})
}
