//! This file was generated by `js-sys-bindgen`.

#![allow(warnings)]

use core::marker::PhantomData;
use crate::{js_bindgen, r#macro, JsValue};
use crate::hazard::{IntoJS, JsCast, OptionIntoJS};
use crate::util::{PtrConst, PtrLength, PtrMut};

#[repr(transparent)]
pub struct JsArray<T = JsValue> {
	value: JsValue,
	_type: PhantomData<T>,
}

impl<T> AsRef<JsValue> for JsArray<T> {
	fn as_ref(&self) -> &JsValue {
		&self.value
	}
}

impl<T> From<JsArray<T>> for JsValue {
	fn from(value: JsArray<T>) -> Self {
		value.value
	}
}

unsafe impl<T> JsCast for JsArray<T> {}

unsafe impl<T> IntoJS for JsArray<T> {
	type Abi = <JsValue as IntoJS>::Abi;

	fn into_abi(self) -> Self::Abi {
		IntoJS::into_abi(JsValue::from(self))
	}
}

unsafe impl<T> OptionIntoJS for JsArray<T> {
	type OptionAbi = <JsValue as OptionIntoJS>::OptionAbi;

	fn option_into_abi(value: ::core::option::Option<Self>) -> Self::OptionAbi {
		OptionIntoJS::option_into_abi(value.map(JsValue::from))
	}
}

impl<T> JsArray<T> {
	pub fn length(self: &JsArray<T>) -> u32 {
		js_bindgen::unsafe_global_wat! {
			"{}", interpolate r#macro::wat_import!(module = "js_sys", import = "length", adapter =
			"js_sys.length", inputs = [("arg0", & JsValue)], output = u32,),
		}

		js_bindgen::import_js! {
			module = "js_sys",
			name = "length",
			required_embeds = [
				r#macro::js_input_embed::<&JsValue>(),
				r#macro::js_output_embed::<u32>(),
				r#macro::js_result_embed::<u32>(),
			],
			"{}",
			interpolate r#macro::js_import!(
				direct_open = r#macro::js_function!("(", ") => ", ("arg0", & JsValue)), direct_call
				= "arg0_0.length", indirect_call = "arg0_0.length", inputs = [("arg0", & JsValue)],
				output = u32,
			),
		}

		unsafe extern "C" {
			#[link_name = "js_sys.length"]
			fn length(
				arg0_0: r#macro::InputSlot1<&JsValue>,
				arg0_1: r#macro::InputSlot2<&JsValue>,
				arg0_2: r#macro::InputSlot3<&JsValue>,
				arg0_3: r#macro::InputSlot4<&JsValue>,
			) -> r#macro::OutputRet<u32>;
		}

		r#macro::join_output({
			let (arg0_0, arg0_1, arg0_2, arg0_3) = unsafe {
				r#macro::split_input_as::<&JsValue>(self)
			};
			unsafe { length(arg0_0, arg0_1, arg0_2, arg0_3) }
		})
	}
}

pub(super) unsafe fn array_js_value_decode(
	array: PtrConst<JsValue>,
	len: PtrLength<JsValue>,
) -> JsArray<JsValue> {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "js_sys", import = "array_js_value_decode",
		adapter = "js_sys.array_js_value_decode", inputs = [("arg0", PtrConst < JsValue >), ("arg1",
		PtrLength < JsValue >)], output = JsArray < JsValue >,),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "array_js_value_decode",
		required_embeds = [
			("js_sys", "array.js_value.decode"),
			r#macro::js_input_embed::<PtrConst<JsValue>>(),
			r#macro::js_input_embed::<PtrLength<JsValue>>(),
			r#macro::js_output_embed::<JsArray<JsValue>>(),
			r#macro::js_result_embed::<JsArray<JsValue>>(),
		],
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "this.#jsEmbed.js_sys['array.js_value.decode']",
			indirect_call = "this.#jsEmbed.js_sys['array.js_value.decode'](arg0_0, arg1_0)", inputs
			= [("arg0", PtrConst < JsValue >), ("arg1", PtrLength < JsValue >)], output = JsArray <
			JsValue >,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.array_js_value_decode"]
		fn array_js_value_decode(
			arg0_0: r#macro::InputSlot1<PtrConst<JsValue>>,
			arg0_1: r#macro::InputSlot2<PtrConst<JsValue>>,
			arg0_2: r#macro::InputSlot3<PtrConst<JsValue>>,
			arg0_3: r#macro::InputSlot4<PtrConst<JsValue>>,
			arg1_0: r#macro::InputSlot1<PtrLength<JsValue>>,
			arg1_1: r#macro::InputSlot2<PtrLength<JsValue>>,
			arg1_2: r#macro::InputSlot3<PtrLength<JsValue>>,
			arg1_3: r#macro::InputSlot4<PtrLength<JsValue>>,
		) -> r#macro::OutputRet<JsArray<JsValue>>;
	}

	r#macro::join_output({
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<PtrConst<JsValue>>(array);
		let (arg1_0, arg1_1, arg1_2, arg1_3) = r#macro::split_input::<PtrLength<JsValue>>(len);
		unsafe {
			array_js_value_decode(arg0_0, arg0_1, arg0_2, arg0_3, arg1_0, arg1_1, arg1_2, arg1_3)
		}
	})
}

pub(super) unsafe fn array_js_value_encode(
	array: &JsArray,
	array_ptr: PtrMut<JsValue>,
	array_len: PtrLength<JsValue>,
	externref_ptr: PtrConst<i32>,
	externref_len: i32,
) -> bool {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "js_sys", import = "array_js_value_encode",
		adapter = "js_sys.array_js_value_encode", inputs = [("arg0", & JsArray), ("arg1", PtrMut <
		JsValue >), ("arg2", PtrLength < JsValue >), ("arg3", PtrConst < i32 >), ("arg4", i32)],
		output = bool,),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "array_js_value_encode",
		required_embeds = [
			("js_sys", "array.js_value.encode"),
			r#macro::js_input_embed::<&JsArray>(),
			r#macro::js_input_embed::<PtrMut<JsValue>>(),
			r#macro::js_input_embed::<PtrLength<JsValue>>(),
			r#macro::js_input_embed::<PtrConst<i32>>(),
			r#macro::js_input_embed::<i32>(),
			r#macro::js_output_embed::<bool>(),
			r#macro::js_result_embed::<bool>(),
		],
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "this.#jsEmbed.js_sys['array.js_value.encode']",
			indirect_call =
			"this.#jsEmbed.js_sys['array.js_value.encode'](arg0_0, arg1_0, arg2_0, arg3_0, arg4_0)",
			inputs = [("arg0", & JsArray), ("arg1", PtrMut < JsValue >), ("arg2", PtrLength <
			JsValue >), ("arg3", PtrConst < i32 >), ("arg4", i32)], output = bool,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.array_js_value_encode"]
		fn array_js_value_encode(
			arg0_0: r#macro::InputSlot1<&JsArray>,
			arg0_1: r#macro::InputSlot2<&JsArray>,
			arg0_2: r#macro::InputSlot3<&JsArray>,
			arg0_3: r#macro::InputSlot4<&JsArray>,
			arg1_0: r#macro::InputSlot1<PtrMut<JsValue>>,
			arg1_1: r#macro::InputSlot2<PtrMut<JsValue>>,
			arg1_2: r#macro::InputSlot3<PtrMut<JsValue>>,
			arg1_3: r#macro::InputSlot4<PtrMut<JsValue>>,
			arg2_0: r#macro::InputSlot1<PtrLength<JsValue>>,
			arg2_1: r#macro::InputSlot2<PtrLength<JsValue>>,
			arg2_2: r#macro::InputSlot3<PtrLength<JsValue>>,
			arg2_3: r#macro::InputSlot4<PtrLength<JsValue>>,
			arg3_0: r#macro::InputSlot1<PtrConst<i32>>,
			arg3_1: r#macro::InputSlot2<PtrConst<i32>>,
			arg3_2: r#macro::InputSlot3<PtrConst<i32>>,
			arg3_3: r#macro::InputSlot4<PtrConst<i32>>,
			arg4_0: r#macro::InputSlot1<i32>,
			arg4_1: r#macro::InputSlot2<i32>,
			arg4_2: r#macro::InputSlot3<i32>,
			arg4_3: r#macro::InputSlot4<i32>,
		) -> r#macro::OutputRet<bool>;
	}

	r#macro::join_output({
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<&JsArray>(array);
		let (arg1_0, arg1_1, arg1_2, arg1_3) = r#macro::split_input::<PtrMut<JsValue>>(array_ptr);
		let (arg2_0, arg2_1, arg2_2, arg2_3) = r#macro::split_input::<
			PtrLength<JsValue>,
		>(array_len);
		let (arg3_0, arg3_1, arg3_2, arg3_3) = r#macro::split_input::<PtrConst<i32>>(externref_ptr);
		let (arg4_0, arg4_1, arg4_2, arg4_3) = r#macro::split_input::<i32>(externref_len);
		unsafe {
			array_js_value_encode(
				arg0_0,
				arg0_1,
				arg0_2,
				arg0_3,
				arg1_0,
				arg1_1,
				arg1_2,
				arg1_3,
				arg2_0,
				arg2_1,
				arg2_2,
				arg2_3,
				arg3_0,
				arg3_1,
				arg3_2,
				arg3_3,
				arg4_0,
				arg4_1,
				arg4_2,
				arg4_3,
			)
		}
	})
}

pub(super) unsafe fn array_u32_decode(array: PtrConst<u32>, len: PtrLength<u32>) -> JsArray<u32> {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "js_sys", import = "array_u32_decode",
		adapter = "js_sys.array_u32_decode", inputs = [("arg0", PtrConst < u32 >), ("arg1",
		PtrLength < u32 >)], output = JsArray < u32 >,),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "array_u32_decode",
		required_embeds = [
			("js_sys", "view.getUint32"),
			r#macro::js_input_embed::<PtrConst<u32>>(),
			r#macro::js_input_embed::<PtrLength<u32>>(),
			r#macro::js_output_embed::<JsArray<u32>>(),
			r#macro::js_result_embed::<JsArray<u32>>(),
		],
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "this.#jsEmbed.js_sys['view.getUint32']", indirect_call
			= "this.#jsEmbed.js_sys['view.getUint32'](arg0_0, arg1_0)", inputs = [("arg0", PtrConst
			< u32 >), ("arg1", PtrLength < u32 >)], output = JsArray < u32 >,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.array_u32_decode"]
		fn array_u32_decode(
			arg0_0: r#macro::InputSlot1<PtrConst<u32>>,
			arg0_1: r#macro::InputSlot2<PtrConst<u32>>,
			arg0_2: r#macro::InputSlot3<PtrConst<u32>>,
			arg0_3: r#macro::InputSlot4<PtrConst<u32>>,
			arg1_0: r#macro::InputSlot1<PtrLength<u32>>,
			arg1_1: r#macro::InputSlot2<PtrLength<u32>>,
			arg1_2: r#macro::InputSlot3<PtrLength<u32>>,
			arg1_3: r#macro::InputSlot4<PtrLength<u32>>,
		) -> r#macro::OutputRet<JsArray<u32>>;
	}

	r#macro::join_output({
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<PtrConst<u32>>(array);
		let (arg1_0, arg1_1, arg1_2, arg1_3) = r#macro::split_input::<PtrLength<u32>>(len);
		unsafe { array_u32_decode(arg0_0, arg0_1, arg0_2, arg0_3, arg1_0, arg1_1, arg1_2, arg1_3) }
	})
}

pub(super) unsafe fn array_u32_encode(
	array: &JsArray<u32>,
	ptr: PtrMut<u32>,
	len: PtrLength<u32>,
) -> bool {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "js_sys", import = "array_u32_encode",
		adapter = "js_sys.array_u32_encode", inputs = [("arg0", & JsArray < u32 >), ("arg1", PtrMut
		< u32 >), ("arg2", PtrLength < u32 >)], output = bool,),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "array_u32_encode",
		required_embeds = [
			("js_sys", "array.u32.encode"),
			r#macro::js_input_embed::<&JsArray<u32>>(),
			r#macro::js_input_embed::<PtrMut<u32>>(),
			r#macro::js_input_embed::<PtrLength<u32>>(),
			r#macro::js_output_embed::<bool>(),
			r#macro::js_result_embed::<bool>(),
		],
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "this.#jsEmbed.js_sys['array.u32.encode']",
			indirect_call = "this.#jsEmbed.js_sys['array.u32.encode'](arg0_0, arg1_0, arg2_0)",
			inputs = [("arg0", & JsArray < u32 >), ("arg1", PtrMut < u32 >), ("arg2", PtrLength <
			u32 >)], output = bool,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.array_u32_encode"]
		fn array_u32_encode(
			arg0_0: r#macro::InputSlot1<&JsArray<u32>>,
			arg0_1: r#macro::InputSlot2<&JsArray<u32>>,
			arg0_2: r#macro::InputSlot3<&JsArray<u32>>,
			arg0_3: r#macro::InputSlot4<&JsArray<u32>>,
			arg1_0: r#macro::InputSlot1<PtrMut<u32>>,
			arg1_1: r#macro::InputSlot2<PtrMut<u32>>,
			arg1_2: r#macro::InputSlot3<PtrMut<u32>>,
			arg1_3: r#macro::InputSlot4<PtrMut<u32>>,
			arg2_0: r#macro::InputSlot1<PtrLength<u32>>,
			arg2_1: r#macro::InputSlot2<PtrLength<u32>>,
			arg2_2: r#macro::InputSlot3<PtrLength<u32>>,
			arg2_3: r#macro::InputSlot4<PtrLength<u32>>,
		) -> r#macro::OutputRet<bool>;
	}

	r#macro::join_output({
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<&JsArray<u32>>(array);
		let (arg1_0, arg1_1, arg1_2, arg1_3) = r#macro::split_input::<PtrMut<u32>>(ptr);
		let (arg2_0, arg2_1, arg2_2, arg2_3) = r#macro::split_input::<PtrLength<u32>>(len);
		unsafe {
			array_u32_encode(
				arg0_0,
				arg0_1,
				arg0_2,
				arg0_3,
				arg1_0,
				arg1_1,
				arg1_2,
				arg1_3,
				arg2_0,
				arg2_1,
				arg2_2,
				arg2_3,
			)
		}
	})
}
