//! This file was generated by `js-sys-bindgen`.

#![allow(warnings)]

//! ```rust
//! # #[js_bindgen_test::test]
//! # fn doctest() {
//! let log = js_sys::JsString::from("hello world");
//! web_sys::console::log(&[log]);
//! # }
//! ````

use js_sys::{js_bindgen, r#macro};
use js_sys::hazard::{Input, Output};
use js_sys::JsValue;
use js_sys::hazard::JsCast;

pub fn log0() {
	js_bindgen::unsafe_embed_asm! {
		"(import \"web_sys\" \"console.log0\" (func $web_sys.import.console.log0 (@sym (name \"web_sys.import.console.log0\"))))",
		"(func $web_sys.console.log0 (@sym)",
		"  call $web_sys.import.console.log0 (@reloc)",
		")",
	}

	js_bindgen::import_js! (module = "web_sys", name = "console.log0", "globalThis.console.log");

	unsafe extern "C" {
		#[link_name = "web_sys.console.log0"]
		fn log0();
	}

	unsafe { log0() };
}

pub fn log<T: JsCast>(data: &[T]) {
	js_bindgen::unsafe_embed_asm! {
		"(import \"web_sys\" \"console.log\" (func $web_sys.import.console.log (@sym (name \"web_sys.import.console.log\")) (param {}))){}",
		"(func $web_sys.console.log (@sym) (param {})",
		"  local.get {}",
		"  call $web_sys.import.console.log (@reloc)",
		")",
		interpolate r#macro::asm_input_import_type::<&[JsValue]>(),
		interpolate r#macro::asm_imports!((&[JsValue])),
		interpolate <&[JsValue] as Input>::ASM_TYPE,
		interpolate r#macro::asm_input!("0", &[JsValue]),
	}

	js_bindgen::import_js! {
		module = "web_sys",
		name = "console.log",
		required_embeds = [r#macro::js_input_embed::<&[JsValue]>()],
		"{}{}{}",
		interpolate r#macro::js_select!("", "(data) => {\n", (&[JsValue])),
		interpolate r#macro::js_parameter!("data", &[JsValue]),
		interpolate r#macro::js_select!(
			"globalThis.console.log",
			"globalThis.console.log(data)\n}",
			(&[JsValue]),
		),
	}

	unsafe extern "C" {
		#[link_name = "web_sys.console.log"]
		fn log(data: <&[JsValue] as Input>::Type);
	}

	unsafe { log(Input::into_raw(data)) };
}

pub fn log2(data1: &JsValue, data2: &JsValue) {
	js_bindgen::unsafe_embed_asm! {
		"(import \"web_sys\" \"console.log2\" (func $web_sys.import.console.log2 (@sym (name \"web_sys.import.console.log2\")) (param {} {}))){}",
		"(func $web_sys.console.log2 (@sym) (param {} {})",
		"  local.get {}",
		"  local.get {}",
		"  call $web_sys.import.console.log2 (@reloc)",
		")",
		interpolate r#macro::asm_input_import_type::<&JsValue>(),
		interpolate r#macro::asm_input_import_type::<&JsValue>(),
		interpolate r#macro::asm_imports!((&JsValue)),
		interpolate <&JsValue as Input>::ASM_TYPE,
		interpolate <&JsValue as Input>::ASM_TYPE,
		interpolate r#macro::asm_input!("0", &JsValue),
		interpolate r#macro::asm_input!("1", &JsValue),
	}

	js_bindgen::import_js! {
		module = "web_sys",
		name = "console.log2",
		required_embeds = [r#macro::js_input_embed::<&JsValue>()],
		"{}{}{}{}",
		interpolate r#macro::js_select!("", "(data1, data2) => {\n", (&JsValue)),
		interpolate r#macro::js_parameter!("data1", &JsValue),
		interpolate r#macro::js_parameter!("data2", &JsValue),
		interpolate r#macro::js_select!(
			"globalThis.console.log",
			"globalThis.console.log(data1, data2)\n}",
			(&JsValue),
		),
	}

	unsafe extern "C" {
		#[link_name = "web_sys.console.log2"]
		fn log2(data1: <&JsValue as Input>::Type, data2: <&JsValue as Input>::Type);
	}

	unsafe { log2(Input::into_raw(data1), Input::into_raw(data2)) };
}

pub fn error(data: &JsValue) {
	js_bindgen::unsafe_embed_asm! {
		"(import \"web_sys\" \"console.error\" (func $web_sys.import.console.error (@sym (name \"web_sys.import.console.error\")) (param {}))){}",
		"(func $web_sys.console.error (@sym) (param {})",
		"  local.get {}",
		"  call $web_sys.import.console.error (@reloc)",
		")",
		interpolate r#macro::asm_input_import_type::<&JsValue>(),
		interpolate r#macro::asm_imports!((&JsValue)),
		interpolate <&JsValue as Input>::ASM_TYPE,
		interpolate r#macro::asm_input!("0", &JsValue),
	}

	js_bindgen::import_js! {
		module = "web_sys",
		name = "console.error",
		required_embeds = [r#macro::js_input_embed::<&JsValue>()],
		"{}{}{}",
		interpolate r#macro::js_select!("", "(data) => {\n", (&JsValue)),
		interpolate r#macro::js_parameter!("data", &JsValue),
		interpolate r#macro::js_select!(
			"globalThis.console.error",
			"globalThis.console.error(data)\n}",
			(&JsValue),
		),
	}

	unsafe extern "C" {
		#[link_name = "web_sys.console.error"]
		fn error(data: <&JsValue as Input>::Type);
	}

	unsafe { error(Input::into_raw(data)) };
}
