//! This file was generated by `js-sys-bindgen`.

#![allow(warnings)]

use js_sys::{js_bindgen, r#macro};
use js_sys::JsValue;
use js_sys::hazard::JsCast;

pub fn log0() {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "web_sys", import = "console.log0", shim =
		"web_sys.console.log0", inputs = [],),
	}

	js_bindgen::import_js! {
		module = "web_sys",
		name = "console.log0",
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "globalThis.console.log", indirect_call =
			"globalThis.console.log()", inputs = [],
		),
	}

	unsafe extern "C" {
		#[link_name = "web_sys.console.log0"]
		fn log0();
	}

	{ unsafe { log0() } };
}

pub fn log<T: JsCast>(data: &[T]) {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "web_sys", import = "console.log", shim =
		"web_sys.console.log", inputs = [("arg0", & [JsValue])],),
	}

	js_bindgen::import_js! {
		module = "web_sys",
		name = "console.log",
		required_embeds = [r#macro::js_input_embed::<&[JsValue]>()],
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "globalThis.console.log", indirect_call =
			"globalThis.console.log(arg0_0)", inputs = [("arg0", & [JsValue])],
		),
	}

	unsafe extern "C" {
		#[link_name = "web_sys.console.log"]
		fn log(
			arg0_0: r#macro::InputSlot1<&[JsValue]>,
			arg0_1: r#macro::InputSlot2<&[JsValue]>,
			arg0_2: r#macro::InputSlot3<&[JsValue]>,
			arg0_3: r#macro::InputSlot4<&[JsValue]>,
		);
	}

	{
		let (arg0_0, arg0_1, arg0_2, arg0_3) = unsafe {
			r#macro::split_input_as::<&[JsValue]>(data)
		};
		unsafe { log(arg0_0, arg0_1, arg0_2, arg0_3) }
	};
}

pub fn log2(data1: &JsValue, data2: &JsValue) {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "web_sys", import = "console.log2", shim =
		"web_sys.console.log2", inputs = [("arg0", & JsValue), ("arg1", & JsValue)],),
	}

	js_bindgen::import_js! {
		module = "web_sys",
		name = "console.log2",
		required_embeds = [r#macro::js_input_embed::<&JsValue>()],
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "globalThis.console.log", indirect_call =
			"globalThis.console.log(arg0_0, arg1_0)", inputs = [("arg0", & JsValue), ("arg1", &
			JsValue)],
		),
	}

	unsafe extern "C" {
		#[link_name = "web_sys.console.log2"]
		fn log2(
			arg0_0: r#macro::InputSlot1<&JsValue>,
			arg0_1: r#macro::InputSlot2<&JsValue>,
			arg0_2: r#macro::InputSlot3<&JsValue>,
			arg0_3: r#macro::InputSlot4<&JsValue>,
			arg1_0: r#macro::InputSlot1<&JsValue>,
			arg1_1: r#macro::InputSlot2<&JsValue>,
			arg1_2: r#macro::InputSlot3<&JsValue>,
			arg1_3: r#macro::InputSlot4<&JsValue>,
		);
	}

	{
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<&JsValue>(data1);
		let (arg1_0, arg1_1, arg1_2, arg1_3) = r#macro::split_input::<&JsValue>(data2);
		unsafe { log2(arg0_0, arg0_1, arg0_2, arg0_3, arg1_0, arg1_1, arg1_2, arg1_3) }
	};
}

pub fn error(data: &JsValue) {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "web_sys", import = "console.error", shim =
		"web_sys.console.error", inputs = [("arg0", & JsValue)],),
	}

	js_bindgen::import_js! {
		module = "web_sys",
		name = "console.error",
		required_embeds = [r#macro::js_input_embed::<&JsValue>()],
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "globalThis.console.error", indirect_call =
			"globalThis.console.error(arg0_0)", inputs = [("arg0", & JsValue)],
		),
	}

	unsafe extern "C" {
		#[link_name = "web_sys.console.error"]
		fn error(
			arg0_0: r#macro::InputSlot1<&JsValue>,
			arg0_1: r#macro::InputSlot2<&JsValue>,
			arg0_2: r#macro::InputSlot3<&JsValue>,
			arg0_3: r#macro::InputSlot4<&JsValue>,
		);
	}

	{
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<&JsValue>(data);
		unsafe { error(arg0_0, arg0_1, arg0_2, arg0_3) }
	};
}
