//! This file was generated by `js-sys-bindgen`.
#![allow(warnings)]
//! ```rust
//! # #[js_bindgen_test::test]
//! # fn doctest() {
//! let log = js_sys::JsString::from_str("hello world");
//! web_sys::console::log(&log);
//! # }
//! ````
use js_sys::hazard::{Input, Output};
use js_sys::{JsValue, js_bindgen, r#macro};
pub fn log0() {
	js_bindgen::unsafe_embed_asm! {
		".import_module web_sys.import.console.log0, web_sys",
		".import_name web_sys.import.console.log0, console.log0",
		".functype web_sys.import.console.log0 () -> ()", "",
		".globl web_sys.console.log0", "web_sys.console.log0:",
		"\t.functype web_sys.console.log0 () -> ()",
		"\tcall web_sys.import.console.log0", "\tend_function",
	}
	js_bindgen::import_js!(name = "console.log0", "globalThis.console.log");
	unsafe extern "C" {
		#[link_name = "web_sys.console.log0"]
		fn log0();
	}
	unsafe { log0() };
}
pub fn log(data: &JsValue) {
	js_bindgen::unsafe_embed_asm! {
		".import_module web_sys.import.console.log, web_sys",
		".import_name web_sys.import.console.log, console.log",
		".functype web_sys.import.console.log ({}) -> ()", "", "{}", "",
		".globl web_sys.console.log", "web_sys.console.log:",
		"\t.functype web_sys.console.log ({}) -> ()", "\tlocal.get 0", "\t{}",
		"\tcall web_sys.import.console.log", "\tend_function", interpolate < & JsValue as
		Input > ::IMPORT_TYPE, interpolate < & JsValue as Input > ::IMPORT_FUNC,
		interpolate < & JsValue as Input > ::TYPE, interpolate < & JsValue as Input >
		::CONV,
	}
	js_bindgen::import_js! {
		name = "console.log", "{}{}{}{}{}", interpolate
		r#macro::select("globalThis.console.log", "(data) => {\n", [< & JsValue as Input
		> ::JS_CONV]), interpolate r#macro::select("", "\tdata", [< & JsValue as Input >
		::JS_CONV]), interpolate r#macro::select("", < & JsValue as Input > ::JS_CONV, [<
		& JsValue as Input > ::JS_CONV]), interpolate r#macro::select("", "\n", [< &
		JsValue as Input > ::JS_CONV]), interpolate r#macro::select("",
		"\tglobalThis.console.log(data)\n}", [< & JsValue as Input > ::JS_CONV]),
	}
	unsafe extern "C" {
		#[link_name = "web_sys.console.log"]
		fn log(data: <&JsValue as Input>::Type);
	}
	unsafe { log(Input::into_raw(data)) };
}
pub fn log2(data1: &JsValue, data2: &JsValue) {
	js_bindgen::unsafe_embed_asm! {
		".import_module web_sys.import.console.log2, web_sys",
		".import_name web_sys.import.console.log2, console.log2",
		".functype web_sys.import.console.log2 ({}, {}) -> ()", "", "{}", "", "{}", "",
		".globl web_sys.console.log2", "web_sys.console.log2:",
		"\t.functype web_sys.console.log2 ({}, {}) -> ()", "\tlocal.get 0", "\t{}",
		"\tlocal.get 1", "\t{}", "\tcall web_sys.import.console.log2", "\tend_function",
		interpolate < & JsValue as Input > ::IMPORT_TYPE, interpolate < & JsValue as
		Input > ::IMPORT_TYPE, interpolate < & JsValue as Input > ::IMPORT_FUNC,
		interpolate < & JsValue as Input > ::IMPORT_FUNC, interpolate < & JsValue as
		Input > ::TYPE, interpolate < & JsValue as Input > ::TYPE, interpolate < &
		JsValue as Input > ::CONV, interpolate < & JsValue as Input > ::CONV,
	}
	js_bindgen::import_js! {
		name = "console.log2", "{}{}{}{}{}{}{}{}", interpolate
		r#macro::select("globalThis.console.log", "(data1, data2) => {\n", [< & JsValue
		as Input > ::JS_CONV, < & JsValue as Input > ::JS_CONV]), interpolate
		r#macro::select("", "\tdata1", [< & JsValue as Input > ::JS_CONV]), interpolate
		r#macro::select("", < & JsValue as Input > ::JS_CONV, [< & JsValue as Input >
		::JS_CONV]), interpolate r#macro::select("", "\n", [< & JsValue as Input >
		::JS_CONV]), interpolate r#macro::select("", "\tdata2", [< & JsValue as Input >
		::JS_CONV]), interpolate r#macro::select("", < & JsValue as Input > ::JS_CONV, [<
		& JsValue as Input > ::JS_CONV]), interpolate r#macro::select("", "\n", [< &
		JsValue as Input > ::JS_CONV]), interpolate r#macro::select("",
		"\tglobalThis.console.log(data1, data2)\n}", [< & JsValue as Input > ::JS_CONV, <
		& JsValue as Input > ::JS_CONV]),
	}
	unsafe extern "C" {
		#[link_name = "web_sys.console.log2"]
		fn log2(data1: <&JsValue as Input>::Type, data2: <&JsValue as Input>::Type);
	}
	unsafe { log2(Input::into_raw(data1), Input::into_raw(data2)) };
}
pub fn error(data: &JsValue) {
	js_bindgen::unsafe_embed_asm! {
		".import_module web_sys.import.console.error, web_sys",
		".import_name web_sys.import.console.error, console.error",
		".functype web_sys.import.console.error ({}) -> ()", "", "{}", "",
		".globl web_sys.console.error", "web_sys.console.error:",
		"\t.functype web_sys.console.error ({}) -> ()", "\tlocal.get 0", "\t{}",
		"\tcall web_sys.import.console.error", "\tend_function", interpolate < & JsValue
		as Input > ::IMPORT_TYPE, interpolate < & JsValue as Input > ::IMPORT_FUNC,
		interpolate < & JsValue as Input > ::TYPE, interpolate < & JsValue as Input >
		::CONV,
	}
	js_bindgen::import_js! {
		name = "console.error", "{}{}{}{}{}", interpolate
		r#macro::select("globalThis.console.error", "(data) => {\n", [< & JsValue as
		Input > ::JS_CONV]), interpolate r#macro::select("", "\tdata", [< & JsValue as
		Input > ::JS_CONV]), interpolate r#macro::select("", < & JsValue as Input >
		::JS_CONV, [< & JsValue as Input > ::JS_CONV]), interpolate r#macro::select("",
		"\n", [< & JsValue as Input > ::JS_CONV]), interpolate r#macro::select("",
		"\tglobalThis.console.error(data)\n}", [< & JsValue as Input > ::JS_CONV]),
	}
	unsafe extern "C" {
		#[link_name = "web_sys.console.error"]
		fn error(data: <&JsValue as Input>::Type);
	}
	unsafe { error(Input::into_raw(data)) };
}
