use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::Args;
use serde::Deserialize;

#[derive(Args)]
pub struct Codegen {
	#[arg(long)]
	input: PathBuf,
	#[arg(long)]
	output_dir: PathBuf,
}

#[derive(Deserialize)]
struct Spec {
	#[serde(default)]
	imports: Vec<JsEntry>,
	#[serde(default)]
	embeds: Vec<JsEntry>,
}

#[derive(Deserialize)]
struct JsEntry {
	module: String,
	name: String,
	#[serde(default)]
	required_embeds: Vec<RequiredEmbed>,
	js: String,
}

#[derive(Deserialize)]
struct RequiredEmbed {
	module: String,
	name: String,
}

impl Codegen {
	pub fn execute(self) -> Result<()> {
		let spec = read_spec(&self.input)?;
		let wat = generate_wat(&spec);
		let name = self
			.input
			.file_stem()
			.and_then(|name| name.to_str())
			.with_context(|| format!("failed to get file stem from `{}`", self.input.display()))?;

		let path = self.output_dir.join(format!("{name}.wat"));
		fs::write(&path, wat).with_context(|| format!("failed to write `{}`", path.display()))?;
		println!("generated {}", path.display());

		Ok(())
	}
}

fn read_spec(path: &Path) -> Result<Spec> {
	let input =
		fs::read_to_string(path).with_context(|| format!("failed to read `{}`", path.display()))?;

	ron::from_str(&input).with_context(|| format!("failed to parse `{}`", path.display()))
}

fn generate_wat(spec: &Spec) -> String {
	let mut output = String::from(
		";; @generated by `cargo run -p js-bindgen-dev -- codegen --input <spec> --output-dir \
		 <dir>`.\n;; Do not edit by hand.\n\n",
	);

	format_section(&mut output, "js_bindgen.import", &spec.imports);
	format_section(&mut output, "js_bindgen.embed", &spec.embeds);

	output
}

fn format_section(output: &mut String, section: &str, entries: &[JsEntry]) {
	if entries.is_empty() {
		return;
	}

	writeln!(output, "(@custom {section:?}").unwrap();

	for entry in entries {
		format_entry(output, entry);
	}

	writeln!(output, ")").unwrap();
}

fn format_entry(output: &mut String, entry: &JsEntry) {
	let record_len = record_len(entry);

	writeln!(output, "  ;; {}:{}", entry.module, entry.name).unwrap();
	writeln!(output, "  ;; record length: {record_len}").unwrap();
	write_binary_string(output, &record_len.to_le_bytes());
	writeln!(output).unwrap();

	writeln!(output, "  ;; module = {:?}", entry.module).unwrap();
	write_len_prefixed_string(output, &entry.module);
	writeln!(output).unwrap();

	writeln!(output, "  ;; name = {:?}", entry.name).unwrap();
	write_len_prefixed_string(output, &entry.name);
	writeln!(output).unwrap();

	writeln!(
		output,
		"  ;; required_embeds = {}",
		entry.required_embeds.len()
	)
	.unwrap();
	write_binary_string(output, &[entry.required_embeds.len() as u8]);
	for embed in &entry.required_embeds {
		write_len_prefixed_string(output, &embed.module);
		write_len_prefixed_string(output, &embed.name);
	}
	writeln!(output).unwrap();

	writeln!(output, "  ;; js").unwrap();
	let mut lines = entry.js.lines().peekable();
	while let Some(line) = lines.next() {
		write_text_string(output, line, lines.peek().is_some());
	}
	writeln!(output).unwrap();
}

fn record_len(entry: &JsEntry) -> u32 {
	let mut len = 0usize;
	len += 2 + entry.module.len();
	len += 2 + entry.name.len();
	len += 1;

	for embed in &entry.required_embeds {
		len += 2 + embed.module.len();
		len += 2 + embed.name.len();
	}
	len += entry.js.len();

	len as u32
}

fn write_len_prefixed_string(output: &mut String, value: &str) {
	write_binary_string(output, &(value.len() as u16).to_le_bytes());
	write_text_string(output, value, false);
}

fn write_binary_string(output: &mut String, bytes: &[u8]) {
	output.push_str("  \"");

	for byte in bytes {
		write!(output, "\\{byte:02x}").unwrap();
	}

	output.push_str("\"\n");
}

fn write_text_string(output: &mut String, value: &str, newline: bool) {
	output.push_str("  \"");

	for byte in value.bytes() {
		match byte {
			b'"' => output.push_str("\\\""),
			b'\\' => output.push_str("\\\\"),
			0x20..=0x7e => output.push(byte.into()),
			_ => write!(output, "\\{byte:02x}").unwrap(),
		}
	}

	if newline {
		output.push_str("\\0a");
	}

	output.push_str("\"\n");
}
