//! This program generates the `wasm-ld` options we require to parse `wasm-ld`
//! arguments.
//!
//! The input is a JSON file produced by running:
//! ```sh
//! llvm-tblgen --dump-json lld/wasm/Options.td -o options.json -I llvm/include
//! ```
//!
//! Then you can run this program:
//! ```sh
//! cargo run -p wasm-ld-opt -- <path to your JSON>
//! ```

use std::collections::BTreeMap;
use std::fs::File;
use std::io::Write;
use std::path::Path;
use std::{env, fs};

use anyhow::{Result, bail};
use proc_macro2::Span;
use quote::quote;
use serde_json::Value;
use syn::{Ident, LitStr};

fn main() -> Result<()> {
	let opt_table: BTreeMap<String, Value> = serde_json::from_slice(&fs::read(
		env::args_os()
			.nth(1)
			.expect("path to JSON file should be present"),
	)?)?;
	let mut args = Vec::new();

	for option in opt_table.values() {
		if let Some(name) = option.get("Name").and_then(|n| n.as_str())
			&& let Some(kind) = option
				.get("Kind")
				.and_then(|def| def.get("def"))
				.and_then(|s| s.as_str())
		{
			let kind = match kind {
				"KIND_COMMAJOINED" => "CommaJoined",
				"KIND_FLAG" => "Flag",
				"KIND_JOINED" => "Joined",
				"KIND_JOINED_OR_SEPARATE" => "JoinedOrSeparate",
				"KIND_SEPARATE" => "Separate",
				// We don't want to handle those.
				"KIND_INPUT" | "KIND_UNKNOWN" => {
					continue;
				}
				kind => bail!("unrecognized `OptionKind`: `{kind}`"),
			};

			args.push((name, kind));
		}
	}

	let length = args.len() + 1;
	let arg_name = args
		.iter()
		.map(|(name, _)| LitStr::new(name, Span::call_site()));
	let arg_flag = args
		.iter()
		.map(|(_, flag)| Ident::new(flag, Span::call_site()));

	let output = quote! {
		const OPT_KIND: [(&str, OptKind); #length] = [
			// Relevant `rust-ld` arguments.
			("flavor", OptKind::Separate),
			// `wasm-ld` arguments.
			#((#arg_name, OptKind::#arg_flag)),*
		];
	};
	let output = syn::parse2(output)?;
	let output = prettyplease::unparse(&output);

	let root = env::var_os("CARGO_MANIFEST_DIR").unwrap();
	let root = Path::new(&root);
	let mut output_file =
		File::create(root.parent().unwrap().join("ld").join("src").join("opt.rs"))?;
	writeln!(output_file, "// Generated by `wasm-ld-opt`.\n\n{output}")?;
	output_file.sync_all()?;

	Ok(())
}
