//! This file was generated by `js-sys-bindgen`.
#![allow(warnings)]
use crate::{js_bindgen, r#macro};
use crate::hazard::{Input, Output};
use super::JsValue;
use crate::util::PtrLength;
pub(super) fn js_value_partial_eq(value1: &JsValue, value2: &JsValue) -> bool {
    js_bindgen::unsafe_embed_asm! {
        ".import_module js_sys.import.js_value_partial_eq, js_sys",
        ".import_name js_sys.import.js_value_partial_eq, js_value_partial_eq",
        ".functype js_sys.import.js_value_partial_eq ({}, {}) -> ({})", "", "{}", "",
        "{}", "", "{}", "", ".globl js_sys.js_value_partial_eq",
        "js_sys.js_value_partial_eq:",
        "\t.functype js_sys.js_value_partial_eq ({}, {}) -> ({})", "\tlocal.get 0",
        "\t{}", "\tlocal.get 1", "\t{}", "\tcall js_sys.import.js_value_partial_eq",
        "\t{}", "\tend_function", interpolate < & JsValue as Input > ::IMPORT_TYPE,
        interpolate < & JsValue as Input > ::IMPORT_TYPE, interpolate < bool as Output >
        ::IMPORT_TYPE, interpolate < & JsValue as Input > ::IMPORT_FUNC, interpolate < &
        JsValue as Input > ::IMPORT_FUNC, interpolate < bool as Output > ::IMPORT_FUNC,
        interpolate < & JsValue as Input > ::TYPE, interpolate < & JsValue as Input >
        ::TYPE, interpolate < bool as Output > ::TYPE, interpolate < & JsValue as Input >
        ::CONV, interpolate < & JsValue as Input > ::CONV, interpolate < bool as Output >
        ::CONV,
    }
    js_bindgen::import_js! {
        module = "js_sys", name = "js_value_partial_eq", required_embeds = [("js_sys",
        "js_value.partial_eq"), (< & JsValue as Input > ::JS_CONV_EMBED.0, < & JsValue as
        Input > ::JS_CONV_EMBED.1), (< & JsValue as Input > ::JS_CONV_EMBED.0, < &
        JsValue as Input > ::JS_CONV_EMBED.1)], "{}{}{}{}{}{}{}{}{}{}{}{}", interpolate
        r#macro::select("this.#jsEmbed.js_sys['js_value.partial_eq']",
        "(value1, value2) => {\n", & [< & JsValue as Input > ::JS_CONV, < & JsValue as
        Input > ::JS_CONV]), interpolate r#macro::select("", "\tvalue1", & [< & JsValue
        as Input > ::JS_CONV]), interpolate r#macro::select("", < & JsValue as Input >
        ::JS_CONV, & [< & JsValue as Input > ::JS_CONV]), interpolate r#macro::select("",
        "value1", & [< & JsValue as Input > ::JS_CONV_POST]), interpolate
        r#macro::select("", < & JsValue as Input > ::JS_CONV_POST, & [< & JsValue as
        Input > ::JS_CONV_POST]), interpolate r#macro::select("", "\n", & [< & JsValue as
        Input > ::JS_CONV]), interpolate r#macro::select("", "\tvalue2", & [< & JsValue
        as Input > ::JS_CONV]), interpolate r#macro::select("", < & JsValue as Input >
        ::JS_CONV, & [< & JsValue as Input > ::JS_CONV]), interpolate r#macro::select("",
        "value2", & [< & JsValue as Input > ::JS_CONV_POST]), interpolate
        r#macro::select("", < & JsValue as Input > ::JS_CONV_POST, & [< & JsValue as
        Input > ::JS_CONV_POST]), interpolate r#macro::select("", "\n", & [< & JsValue as
        Input > ::JS_CONV]), interpolate r#macro::select("",
        "\treturn this.#jsEmbed.js_sys['js_value.partial_eq'](value1, value2)\n}", & [< &
        JsValue as Input > ::JS_CONV, < & JsValue as Input > ::JS_CONV]),
    }
    unsafe extern "C" {
        #[link_name = "js_sys.js_value_partial_eq"]
        fn js_value_partial_eq(
            value1: <&JsValue as Input>::Type,
            value2: <&JsValue as Input>::Type,
        ) -> <bool as Output>::Type;
    }
    Output::from_raw(unsafe {
        js_value_partial_eq(Input::into_raw(value1), Input::into_raw(value2))
    })
}
