//! This file was generated by `js-sys-bindgen`.

#![allow(warnings)]

use crate::{js_bindgen, r#macro};
use super::JsValue;
use crate::util::PtrLength;

pub(super) fn js_value_partial_eq(value1: &JsValue, value2: &JsValue) -> bool {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "js_sys", import = "js_value_partial_eq",
		adapter = "js_sys.js_value_partial_eq", inputs = [("arg0", & JsValue), ("arg1", & JsValue)],
		output = bool,),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "js_value_partial_eq",
		required_embeds = [
			("js_sys", "js_value.partial_eq"),
			r#macro::js_input_embed::<&JsValue>(),
			r#macro::js_output_embed::<bool>(),
			r#macro::js_result_embed::<bool>(),
		],
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "this.#jsEmbed.js_sys['js_value.partial_eq']",
			indirect_call = "this.#jsEmbed.js_sys['js_value.partial_eq'](arg0_0, arg1_0)", inputs =
			[("arg0", & JsValue), ("arg1", & JsValue)], output = bool,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.js_value_partial_eq"]
		fn js_value_partial_eq(
			arg0_0: r#macro::InputSlot1<&JsValue>,
			arg0_1: r#macro::InputSlot2<&JsValue>,
			arg0_2: r#macro::InputSlot3<&JsValue>,
			arg0_3: r#macro::InputSlot4<&JsValue>,
			arg1_0: r#macro::InputSlot1<&JsValue>,
			arg1_1: r#macro::InputSlot2<&JsValue>,
			arg1_2: r#macro::InputSlot3<&JsValue>,
			arg1_3: r#macro::InputSlot4<&JsValue>,
		) -> r#macro::OutputRet<bool>;
	}

	r#macro::join_output({
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<&JsValue>(value1);
		let (arg1_0, arg1_1, arg1_2, arg1_3) = r#macro::split_input::<&JsValue>(value2);
		unsafe {
			js_value_partial_eq(arg0_0, arg0_1, arg0_2, arg0_3, arg1_0, arg1_1, arg1_2, arg1_3)
		}
	})
}
