//! This file was generated by `js-sys-bindgen`.

#![allow(warnings)]

use crate::{js_bindgen, r#macro, JsValue};
use crate::hazard::{IntoJS, JsCast, OptionIntoJS};
use crate::util::{PtrConst, PtrLength, PtrMut};

#[derive(Clone, Debug)]
#[repr(transparent)]
pub struct JsString(JsValue);

impl AsRef<JsValue> for JsString {
	fn as_ref(&self) -> &JsValue {
		&self.0
	}
}

impl From<JsString> for JsValue {
	fn from(value: JsString) -> Self {
		value.0
	}
}

unsafe impl JsCast for JsString {}

unsafe impl IntoJS for JsString {
	type Abi = <JsValue as IntoJS>::Abi;

	fn into_abi(self) -> Self::Abi {
		IntoJS::into_abi(JsValue::from(self))
	}
}

unsafe impl OptionIntoJS for JsString {
	type OptionAbi = <JsValue as OptionIntoJS>::OptionAbi;

	fn option_into_abi(value: ::core::option::Option<Self>) -> Self::OptionAbi {
		OptionIntoJS::option_into_abi(value.map(JsValue::from))
	}
}

pub(super) fn string_constructor(value: &JsValue) -> JsString {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "js_sys", import = "string_constructor",
		adapter = "js_sys.string_constructor", inputs = [("arg0", & JsValue)], output = JsString,),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "string_constructor",
		required_embeds = [
			r#macro::js_input_embed::<&JsValue>(),
			r#macro::js_output_embed::<JsString>(),
			r#macro::js_result_embed::<JsString>(),
		],
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "globalThis.String", indirect_call =
			"globalThis.String(arg0_0)", inputs = [("arg0", & JsValue)], output = JsString,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.string_constructor"]
		fn string_constructor(
			arg0_0: r#macro::InputSlot1<&JsValue>,
			arg0_1: r#macro::InputSlot2<&JsValue>,
			arg0_2: r#macro::InputSlot3<&JsValue>,
			arg0_3: r#macro::InputSlot4<&JsValue>,
		) -> r#macro::OutputRet<JsString>;
	}

	r#macro::join_output({
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<&JsValue>(value);
		unsafe { string_constructor(arg0_0, arg0_1, arg0_2, arg0_3) }
	})
}

pub(super) unsafe fn string_eq(string: &JsString, array: PtrConst<u8>, len: PtrLength<u8>) -> bool {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "js_sys", import = "string_eq", adapter =
		"js_sys.string_eq", inputs = [("arg0", & JsString), ("arg1", PtrConst < u8 >), ("arg2",
		PtrLength < u8 >)], output = bool,),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "string_eq",
		required_embeds = [
			("js_sys", "string.eq"),
			r#macro::js_input_embed::<&JsString>(),
			r#macro::js_input_embed::<PtrConst<u8>>(),
			r#macro::js_input_embed::<PtrLength<u8>>(),
			r#macro::js_output_embed::<bool>(),
			r#macro::js_result_embed::<bool>(),
		],
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "this.#jsEmbed.js_sys['string.eq']", indirect_call =
			"this.#jsEmbed.js_sys['string.eq'](arg0_0, arg1_0, arg2_0)", inputs = [("arg0", &
			JsString), ("arg1", PtrConst < u8 >), ("arg2", PtrLength < u8 >)], output = bool,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.string_eq"]
		fn string_eq(
			arg0_0: r#macro::InputSlot1<&JsString>,
			arg0_1: r#macro::InputSlot2<&JsString>,
			arg0_2: r#macro::InputSlot3<&JsString>,
			arg0_3: r#macro::InputSlot4<&JsString>,
			arg1_0: r#macro::InputSlot1<PtrConst<u8>>,
			arg1_1: r#macro::InputSlot2<PtrConst<u8>>,
			arg1_2: r#macro::InputSlot3<PtrConst<u8>>,
			arg1_3: r#macro::InputSlot4<PtrConst<u8>>,
			arg2_0: r#macro::InputSlot1<PtrLength<u8>>,
			arg2_1: r#macro::InputSlot2<PtrLength<u8>>,
			arg2_2: r#macro::InputSlot3<PtrLength<u8>>,
			arg2_3: r#macro::InputSlot4<PtrLength<u8>>,
		) -> r#macro::OutputRet<bool>;
	}

	r#macro::join_output({
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<&JsString>(string);
		let (arg1_0, arg1_1, arg1_2, arg1_3) = r#macro::split_input::<PtrConst<u8>>(array);
		let (arg2_0, arg2_1, arg2_2, arg2_3) = r#macro::split_input::<PtrLength<u8>>(len);
		unsafe {
			string_eq(
				arg0_0,
				arg0_1,
				arg0_2,
				arg0_3,
				arg1_0,
				arg1_1,
				arg1_2,
				arg1_3,
				arg2_0,
				arg2_1,
				arg2_2,
				arg2_3,
			)
		}
	})
}

pub(super) unsafe fn string_decode(array: PtrConst<u8>, len: PtrLength<u8>) -> JsString {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "js_sys", import = "string_decode", adapter
		= "js_sys.string_decode", inputs = [("arg0", PtrConst < u8 >), ("arg1", PtrLength < u8 >)],
		output = JsString,),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "string_decode",
		required_embeds = [
			("js_sys", "string.decode"),
			r#macro::js_input_embed::<PtrConst<u8>>(),
			r#macro::js_input_embed::<PtrLength<u8>>(),
			r#macro::js_output_embed::<JsString>(),
			r#macro::js_result_embed::<JsString>(),
		],
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "this.#jsEmbed.js_sys['string.decode']", indirect_call =
			"this.#jsEmbed.js_sys['string.decode'](arg0_0, arg1_0)", inputs = [("arg0", PtrConst <
			u8 >), ("arg1", PtrLength < u8 >)], output = JsString,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.string_decode"]
		fn string_decode(
			arg0_0: r#macro::InputSlot1<PtrConst<u8>>,
			arg0_1: r#macro::InputSlot2<PtrConst<u8>>,
			arg0_2: r#macro::InputSlot3<PtrConst<u8>>,
			arg0_3: r#macro::InputSlot4<PtrConst<u8>>,
			arg1_0: r#macro::InputSlot1<PtrLength<u8>>,
			arg1_1: r#macro::InputSlot2<PtrLength<u8>>,
			arg1_2: r#macro::InputSlot3<PtrLength<u8>>,
			arg1_3: r#macro::InputSlot4<PtrLength<u8>>,
		) -> r#macro::OutputRet<JsString>;
	}

	r#macro::join_output({
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<PtrConst<u8>>(array);
		let (arg1_0, arg1_1, arg1_2, arg1_3) = r#macro::split_input::<PtrLength<u8>>(len);
		unsafe { string_decode(arg0_0, arg0_1, arg0_2, arg0_3, arg1_0, arg1_1, arg1_2, arg1_3) }
	})
}

pub(super) fn string_utf8_length(string: &JsString) -> f64 {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "js_sys", import = "string_utf8_length",
		adapter = "js_sys.string_utf8_length", inputs = [("arg0", & JsString)], output = f64,),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "string_utf8_length",
		required_embeds = [
			("js_sys", "string.utf8_length"),
			r#macro::js_input_embed::<&JsString>(),
			r#macro::js_output_embed::<f64>(),
			r#macro::js_result_embed::<f64>(),
		],
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "this.#jsEmbed.js_sys['string.utf8_length']",
			indirect_call = "this.#jsEmbed.js_sys['string.utf8_length'](arg0_0)", inputs = [("arg0",
			& JsString)], output = f64,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.string_utf8_length"]
		fn string_utf8_length(
			arg0_0: r#macro::InputSlot1<&JsString>,
			arg0_1: r#macro::InputSlot2<&JsString>,
			arg0_2: r#macro::InputSlot3<&JsString>,
			arg0_3: r#macro::InputSlot4<&JsString>,
		) -> r#macro::OutputRet<f64>;
	}

	r#macro::join_output({
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<&JsString>(string);
		unsafe { string_utf8_length(arg0_0, arg0_1, arg0_2, arg0_3) }
	})
}

pub(super) unsafe fn string_encode(string: &JsString, array: PtrMut<u8>, len: PtrLength<u8>) {
	js_bindgen::unsafe_global_wat! {
		"{}", interpolate r#macro::wat_import!(module = "js_sys", import = "string_encode", adapter
		= "js_sys.string_encode", inputs = [("arg0", & JsString), ("arg1", PtrMut < u8 >), ("arg2",
		PtrLength < u8 >)],),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "string_encode",
		required_embeds = [
			("js_sys", "string.encode"),
			r#macro::js_input_embed::<&JsString>(),
			r#macro::js_input_embed::<PtrMut<u8>>(),
			r#macro::js_input_embed::<PtrLength<u8>>(),
		],
		"{}",
		interpolate r#macro::js_import!(
			direct_open = "", direct_call = "this.#jsEmbed.js_sys['string.encode']", indirect_call =
			"this.#jsEmbed.js_sys['string.encode'](arg0_0, arg1_0, arg2_0)", inputs = [("arg0", &
			JsString), ("arg1", PtrMut < u8 >), ("arg2", PtrLength < u8 >)],
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.string_encode"]
		fn string_encode(
			arg0_0: r#macro::InputSlot1<&JsString>,
			arg0_1: r#macro::InputSlot2<&JsString>,
			arg0_2: r#macro::InputSlot3<&JsString>,
			arg0_3: r#macro::InputSlot4<&JsString>,
			arg1_0: r#macro::InputSlot1<PtrMut<u8>>,
			arg1_1: r#macro::InputSlot2<PtrMut<u8>>,
			arg1_2: r#macro::InputSlot3<PtrMut<u8>>,
			arg1_3: r#macro::InputSlot4<PtrMut<u8>>,
			arg2_0: r#macro::InputSlot1<PtrLength<u8>>,
			arg2_1: r#macro::InputSlot2<PtrLength<u8>>,
			arg2_2: r#macro::InputSlot3<PtrLength<u8>>,
			arg2_3: r#macro::InputSlot4<PtrLength<u8>>,
		);
	}

	{
		let (arg0_0, arg0_1, arg0_2, arg0_3) = r#macro::split_input::<&JsString>(string);
		let (arg1_0, arg1_1, arg1_2, arg1_3) = r#macro::split_input::<PtrMut<u8>>(array);
		let (arg2_0, arg2_1, arg2_2, arg2_3) = r#macro::split_input::<PtrLength<u8>>(len);
		unsafe {
			string_encode(
				arg0_0,
				arg0_1,
				arg0_2,
				arg0_3,
				arg1_0,
				arg1_1,
				arg1_2,
				arg1_3,
				arg2_0,
				arg2_1,
				arg2_2,
				arg2_3,
			)
		}
	};
}
