//! This file was generated by `js-sys-bindgen`.

#![allow(warnings)]

use core::ops::Deref;
use crate::{js_bindgen, r#macro, JsValue};
use crate::hazard::{Input, InputJsConv, InputAsmConv, OutputAsmConv, Output, OutputJsConv};
use crate::util::PtrLength;

#[derive(Clone, Debug)]
#[repr(transparent)]
pub struct JsString(JsValue);

impl Deref for JsString {
	type Target = JsValue;

	fn deref(&self) -> &Self::Target {
		&self.0
	}
}

impl From<JsString> for JsValue {
	fn from(value: JsString) -> Self {
		value.0
	}
}

unsafe impl Input for &JsString {
	const ASM_TYPE: &'static str = <&JsValue as Input>::ASM_TYPE;
	const ASM_CONV: Option<InputAsmConv> = <&JsValue as Input>::ASM_CONV;
	const JS_CONV: Option<InputJsConv> = <&JsValue as Input>::JS_CONV;

	type Type = <&'static JsValue as Input>::Type;

	fn into_raw(self) -> Self::Type {
		Input::into_raw(&self.0)
	}
}

unsafe impl Output for JsString {
	const ASM_TYPE: &str = <JsValue as Output>::ASM_TYPE;
	const ASM_CONV: Option<OutputAsmConv> = <JsValue as Output>::ASM_CONV;
	const JS_CONV: Option<OutputJsConv> = <JsValue as Output>::JS_CONV;

	type Type = <JsValue as Output>::Type;

	fn from_raw(raw: Self::Type) -> Self {
		Self(Output::from_raw(raw))
	}
}

impl JsString {
	#[must_use]
	pub fn unchecked_from(value: JsValue) -> Self {
		Self(value)
	}
}

pub(super) fn string_constructor(value: &JsValue) -> JsString {
	js_bindgen::unsafe_embed_asm! {
		"(module (@rwat)",
		"  (import \"js_sys\" \"string_constructor\" (func $js_sys.import.string_constructor (@sym) (param {}) (result {})))",
		"  {}",
		"",
		"  {}",
		"",
		"  (func $js_sys.string_constructor (@sym) (param {} {}) (result {})",
		"    local.get {}",
		"    call $js_sys.import.string_constructor (@reloc)",
		"    {}",
		"  )",
		")",
		interpolate r#macro::asm_input_import_type::<&JsValue>(),
		interpolate r#macro::asm_output_import_type::<JsString>(),
		interpolate r#macro::asm_input_import::<&JsValue>(),
		interpolate r#macro::asm_output_import::<JsString>(),
		interpolate r#macro::asm_indirect!(JsString),
		interpolate <&JsValue as Input>::ASM_TYPE,
		interpolate r#macro::asm_direct::<JsString>(),
		interpolate r#macro::asm_input!("0", "1", &JsValue, JsString),
		interpolate r#macro::asm_output!(JsString),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "string_constructor",
		required_embeds = [
			r#macro::js_input_embed::<&JsValue>(),
			r#macro::js_output_embed::<JsString>(),
		],
		"{}{}{}",
		interpolate r#macro::js_select!("", "(value) => {\n", (&JsValue), JsString),
		interpolate r#macro::js_parameter!("value", &JsValue),
		interpolate r#macro::js_output!(
			"\treturn ",
			"globalThis.String",
			"globalThis.String(value)",
			JsString,
			&JsValue,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.string_constructor"]
		fn string_constructor(value: <&JsValue as Input>::Type) -> <JsString as Output>::Type;
	}

	Output::from_raw(unsafe { string_constructor(Input::into_raw(value)) })
}

pub(super) unsafe fn string_eq(string: &JsString, array: *const u8, len: PtrLength<u8>) -> bool {
	js_bindgen::unsafe_embed_asm! {
		"(module (@rwat)",
		"  (import \"js_sys\" \"string_eq\" (func $js_sys.import.string_eq (@sym) (param {} {} {}) (result {})))",
		"  {}",
		"",
		"  {}",
		"",
		"  {}",
		"",
		"  {}",
		"",
		"  (func $js_sys.string_eq (@sym) (param {} {} {} {}) (result {})",
		"    local.get {}",
		"    local.get {}",
		"    local.get {}",
		"    call $js_sys.import.string_eq (@reloc)",
		"    {}",
		"  )",
		")",
		interpolate r#macro::asm_input_import_type::<&JsString>(),
		interpolate r#macro::asm_input_import_type::<*const u8>(),
		interpolate r#macro::asm_input_import_type::<PtrLength<u8>>(),
		interpolate r#macro::asm_output_import_type::<bool>(),
		interpolate r#macro::asm_input_import::<&JsString>(),
		interpolate r#macro::asm_input_import::<*const u8>(),
		interpolate r#macro::asm_input_import::<PtrLength<u8>>(),
		interpolate r#macro::asm_output_import::<bool>(),
		interpolate r#macro::asm_indirect!(bool),
		interpolate <&JsString as Input>::ASM_TYPE,
		interpolate <*const u8 as Input>::ASM_TYPE,
		interpolate <PtrLength<u8> as Input>::ASM_TYPE,
		interpolate r#macro::asm_direct::<bool>(),
		interpolate r#macro::asm_input!("0", "1", &JsString, bool),
		interpolate r#macro::asm_input!("1", "2", *const u8, bool),
		interpolate r#macro::asm_input!("2", "3", PtrLength<u8>, bool),
		interpolate r#macro::asm_output!(bool),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "string_eq",
		required_embeds = [
			("js_sys", "string.eq"),
			r#macro::js_input_embed::<&JsString>(),
			r#macro::js_input_embed::<*const u8>(),
			r#macro::js_input_embed::<PtrLength<u8>>(),
			r#macro::js_output_embed::<bool>(),
		],
		"{}{}{}{}{}",
		interpolate r#macro::js_select!(
			"",
			"(string, array, len) => {\n",
			(&JsString, *const u8, PtrLength<u8>),
			bool,
		),
		interpolate r#macro::js_parameter!("string", &JsString),
		interpolate r#macro::js_parameter!("array", *const u8),
		interpolate r#macro::js_parameter!("len", PtrLength<u8>),
		interpolate r#macro::js_output!(
			"\treturn ",
			"this.#jsEmbed.js_sys['string.eq']",
			"this.#jsEmbed.js_sys['string.eq'](string, array, len)",
			bool,
			&JsString,
			*const u8,
			PtrLength<u8>,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.string_eq"]
		fn string_eq(
			string: <&JsString as Input>::Type,
			array: <*const u8 as Input>::Type,
			len: <PtrLength<u8> as Input>::Type,
		) -> <bool as Output>::Type;
	}

	Output::from_raw(unsafe {
		string_eq(Input::into_raw(string), Input::into_raw(array), Input::into_raw(len))
	})
}

pub(super) unsafe fn string_decode(array: *const u8, len: PtrLength<u8>) -> JsString {
	js_bindgen::unsafe_embed_asm! {
		"(module (@rwat)",
		"  (import \"js_sys\" \"string_decode\" (func $js_sys.import.string_decode (@sym) (param {} {}) (result {})))",
		"  {}",
		"",
		"  {}",
		"",
		"  {}",
		"",
		"  (func $js_sys.string_decode (@sym) (param {} {} {}) (result {})",
		"    local.get {}",
		"    local.get {}",
		"    call $js_sys.import.string_decode (@reloc)",
		"    {}",
		"  )",
		")",
		interpolate r#macro::asm_input_import_type::<*const u8>(),
		interpolate r#macro::asm_input_import_type::<PtrLength<u8>>(),
		interpolate r#macro::asm_output_import_type::<JsString>(),
		interpolate r#macro::asm_input_import::<*const u8>(),
		interpolate r#macro::asm_input_import::<PtrLength<u8>>(),
		interpolate r#macro::asm_output_import::<JsString>(),
		interpolate r#macro::asm_indirect!(JsString),
		interpolate <*const u8 as Input>::ASM_TYPE,
		interpolate <PtrLength<u8> as Input>::ASM_TYPE,
		interpolate r#macro::asm_direct::<JsString>(),
		interpolate r#macro::asm_input!("0", "1", *const u8, JsString),
		interpolate r#macro::asm_input!("1", "2", PtrLength<u8>, JsString),
		interpolate r#macro::asm_output!(JsString),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "string_decode",
		required_embeds = [
			("js_sys", "string.decode"),
			r#macro::js_input_embed::<*const u8>(),
			r#macro::js_input_embed::<PtrLength<u8>>(),
			r#macro::js_output_embed::<JsString>(),
		],
		"{}{}{}{}",
		interpolate r#macro::js_select!(
			"",
			"(array, len) => {\n",
			(*const u8, PtrLength<u8>),
			JsString,
		),
		interpolate r#macro::js_parameter!("array", *const u8),
		interpolate r#macro::js_parameter!("len", PtrLength<u8>),
		interpolate r#macro::js_output!(
			"\treturn ",
			"this.#jsEmbed.js_sys['string.decode']",
			"this.#jsEmbed.js_sys['string.decode'](array, len)",
			JsString,
			*const u8,
			PtrLength<u8>,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.string_decode"]
		fn string_decode(
			array: <*const u8 as Input>::Type,
			len: <PtrLength<u8> as Input>::Type,
		) -> <JsString as Output>::Type;
	}

	Output::from_raw(unsafe { string_decode(Input::into_raw(array), Input::into_raw(len)) })
}

pub(super) fn string_utf8_length(string: &JsString) -> f64 {
	js_bindgen::unsafe_embed_asm! {
		"(module (@rwat)",
		"  (import \"js_sys\" \"string_utf8_length\" (func $js_sys.import.string_utf8_length (@sym) (param {}) (result {})))",
		"  {}",
		"",
		"  {}",
		"",
		"  (func $js_sys.string_utf8_length (@sym) (param {} {}) (result {})",
		"    local.get {}",
		"    call $js_sys.import.string_utf8_length (@reloc)",
		"    {}",
		"  )",
		")",
		interpolate r#macro::asm_input_import_type::<&JsString>(),
		interpolate r#macro::asm_output_import_type::<f64>(),
		interpolate r#macro::asm_input_import::<&JsString>(),
		interpolate r#macro::asm_output_import::<f64>(),
		interpolate r#macro::asm_indirect!(f64),
		interpolate <&JsString as Input>::ASM_TYPE,
		interpolate r#macro::asm_direct::<f64>(),
		interpolate r#macro::asm_input!("0", "1", &JsString, f64),
		interpolate r#macro::asm_output!(f64),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "string_utf8_length",
		required_embeds = [
			("js_sys", "string.utf8_length"),
			r#macro::js_input_embed::<&JsString>(),
			r#macro::js_output_embed::<f64>(),
		],
		"{}{}{}",
		interpolate r#macro::js_select!("", "(string) => {\n", (&JsString), f64),
		interpolate r#macro::js_parameter!("string", &JsString),
		interpolate r#macro::js_output!(
			"\treturn ",
			"this.#jsEmbed.js_sys['string.utf8_length']",
			"this.#jsEmbed.js_sys['string.utf8_length'](string)",
			f64,
			&JsString,
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.string_utf8_length"]
		fn string_utf8_length(string: <&JsString as Input>::Type) -> <f64 as Output>::Type;
	}

	Output::from_raw(unsafe { string_utf8_length(Input::into_raw(string)) })
}

pub(super) unsafe fn string_encode(string: &JsString, array: *mut u8, len: PtrLength<u8>) {
	js_bindgen::unsafe_embed_asm! {
		"(module (@rwat)",
		"  (import \"js_sys\" \"string_encode\" (func $js_sys.import.string_encode (@sym) (param {} {} {}) (result )))",
		"  {}",
		"",
		"  {}",
		"",
		"  {}",
		"",
		"  (func $js_sys.string_encode (@sym) (param  {} {} {}) (result )",
		"    local.get {}",
		"    local.get {}",
		"    local.get {}",
		"    call $js_sys.import.string_encode (@reloc)",
		"    ",
		"  )",
		")",
		interpolate r#macro::asm_input_import_type::<&JsString>(),
		interpolate r#macro::asm_input_import_type::<*mut u8>(),
		interpolate r#macro::asm_input_import_type::<PtrLength<u8>>(),
		interpolate r#macro::asm_input_import::<&JsString>(),
		interpolate r#macro::asm_input_import::<*mut u8>(),
		interpolate r#macro::asm_input_import::<PtrLength<u8>>(),
		interpolate <&JsString as Input>::ASM_TYPE,
		interpolate <*mut u8 as Input>::ASM_TYPE,
		interpolate <PtrLength<u8> as Input>::ASM_TYPE,
		interpolate r#macro::asm_input!("0", &JsString),
		interpolate r#macro::asm_input!("1", *mut u8),
		interpolate r#macro::asm_input!("2", PtrLength<u8>),
	}

	js_bindgen::import_js! {
		module = "js_sys",
		name = "string_encode",
		required_embeds = [
			("js_sys", "string.encode"),
			r#macro::js_input_embed::<&JsString>(),
			r#macro::js_input_embed::<*mut u8>(),
			r#macro::js_input_embed::<PtrLength<u8>>(),
		],
		"{}{}{}{}{}",
		interpolate r#macro::js_select!(
			"",
			"(string, array, len) => {\n",
			(&JsString, *mut u8, PtrLength<u8>),
		),
		interpolate r#macro::js_parameter!("string", &JsString),
		interpolate r#macro::js_parameter!("array", *mut u8),
		interpolate r#macro::js_parameter!("len", PtrLength<u8>),
		interpolate r#macro::js_select!(
			"this.#jsEmbed.js_sys['string.encode']",
			"this.#jsEmbed.js_sys['string.encode'](string, array, len)\n}",
			(&JsString, *mut u8, PtrLength<u8>),
		),
	}

	unsafe extern "C" {
		#[link_name = "js_sys.string_encode"]
		fn string_encode(
			string: <&JsString as Input>::Type,
			array: <*mut u8 as Input>::Type,
			len: <PtrLength<u8> as Input>::Type,
		);
	}

	unsafe { string_encode(Input::into_raw(string), Input::into_raw(array), Input::into_raw(len)) };
}
