//! This file was generated by `js-sys-bindgen`.

#![allow(warnings)]

use core::marker::PhantomData;
use core::ops::Deref;
use crate::JsValue;
use crate::hazard::{Input, InputJsConv, InputAsmConv, OutputAsmConv, Output, OutputJsConv};

#[repr(transparent)]
pub struct JsNumber<T = f64> {
	value: JsValue,
	_type: PhantomData<T>,
}

impl<T> Deref for JsNumber<T> {
	type Target = JsValue;

	fn deref(&self) -> &Self::Target {
		&self.value
	}
}

impl<T> From<JsNumber<T>> for JsValue {
	fn from(value: JsNumber<T>) -> Self {
		value.value
	}
}

unsafe impl<T> Input for &JsNumber<T> {
	const ASM_TYPE: &'static str = <&JsValue as Input>::ASM_TYPE;
	const ASM_CONV: Option<InputAsmConv> = <&JsValue as Input>::ASM_CONV;
	const JS_CONV: Option<InputJsConv> = <&JsValue as Input>::JS_CONV;

	type Type = <&'static JsValue as Input>::Type;

	fn into_raw(self) -> Self::Type {
		Input::into_raw(&self.value)
	}
}

unsafe impl<T> Output for JsNumber<T> {
	const ASM_TYPE: &str = <JsValue as Output>::ASM_TYPE;
	const ASM_CONV: Option<OutputAsmConv> = <JsValue as Output>::ASM_CONV;
	const JS_CONV: Option<OutputJsConv> = <JsValue as Output>::JS_CONV;

	type Type = <JsValue as Output>::Type;

	fn from_raw(raw: Self::Type) -> Self {
		Self {
			value: Output::from_raw(raw),
			_type: PhantomData,
		}
	}
}

impl<T> JsNumber<T> {
	#[must_use]
	pub fn unchecked_from(value: JsValue) -> Self {
		Self { value, _type: PhantomData }
	}
}
