name: Audit

on:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  rust-sec:
    name: RustSec - ${{ matrix.workspace.name }}

    runs-on: ubuntu-latest

    permissions:
      security-events: write # To create Security Advisories.

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        workspace:
          - { name: Client, path: client }
          - { name: Host, path: host }

    defaults:
      run:
        working-directory: ${{ matrix.workspace.path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install `cargo audit`
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit
      - name: Run `cargo audit`
        run: cargo audit
      - name: Generate SARIF
        if: always()
        run: |
          mkdir ../../results
          cargo audit --format sarif > ../../results/cargo-audit.sarif
      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
