name: CI

on:
  push:
    branches: ["main"]
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  XWIN_ARCH: x86_64

jobs:
  host-tools:
    name: Build Host Tools - ${{ matrix.os.description }}

    runs-on: ${{ matrix.os.os }}

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        os:
          - { os: ubuntu-latest, name: linux, description: Linux }
          - { os: macos-latest, name: mac-os, description: macOS }
          - {
              os: ubuntu-latest,
              name: windows,
              sub-command: xwin,
              args: --target x86_64-pc-windows-msvc,
              exe: .exe,
              path: x86_64-pc-windows-msvc/,
              description: Windows,
            }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Stable Rust Override
        run: cp .github/rust-toolchain.toml .
      - name: Install Target
        if: matrix.os.name == 'windows'
        run: rustup target add x86_64-pc-windows-msvc
      - name: Install `libLLVM`
        if: matrix.os.name == 'windows'
        run: rustup component add llvm-tools
      - name: Install `cargo-xwin`
        if: matrix.os.name == 'windows'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-xwin
      - name: Restore `cargo-xwin` Cache
        if: matrix.os.name == 'windows'
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/cargo-xwin
          key: cargo-xwin-cache-default
      - name: Download `cargo-xwin` Cache
        if: matrix.os.name == 'windows'
        run: cargo xwin cache xwin
      - name: Save `cargo-xwin` Cache
        if: matrix.os.name == 'windows'
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/cargo-xwin
          key: cargo-xwin-cache-default
      - name: Enable Caching
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "cache"
          key: ${{ matrix.os.name }}
          workspaces: host
          cache-bin: false
      - name: Prepare Output Directory
        run: mkdir ${{ runner.temp }}/host-tools
      - name: Build `cargo-js-sys`
        working-directory: host
        run: |
          cargo ${{ matrix.os.sub-command }} build -p cargo-js-sys ${{ matrix.os.args }} --release
          cp target/${{ matrix.os.path }}release/cargo-js-sys${{ matrix.os.exe }} ${{ runner.temp }}/host-tools/
      - name: Build `js-bindgen-ld`
        working-directory: host
        run: |
          cargo ${{ matrix.os.sub-command }} build -p js-bindgen-ld ${{ matrix.os.args }} --release
          cp target/${{ matrix.os.path }}release/js-bindgen-ld${{ matrix.os.exe }} ${{ runner.temp }}/host-tools/
      - name: Build `js-bindgen-runner`
        working-directory: host
        run: |
          cargo ${{ matrix.os.sub-command }} build -p js-bindgen-runner ${{ matrix.os.args }} --release
          cp target/${{ matrix.os.path }}release/js-bindgen-runner${{ matrix.os.exe }} ${{ runner.temp }}/host-tools/
      - name: Build `js-bindgen-web-driver`
        working-directory: host
        run: |
          cargo ${{ matrix.os.sub-command }} build -p js-bindgen-web-driver ${{ matrix.os.args }} --release
          cp target/${{ matrix.os.path }}release/js-bindgen-web-driver${{ matrix.os.exe }} ${{ runner.temp }}/host-tools/
      - name: Build `js-bindgen-dev`
        working-directory: host
        run: |
          cargo ${{ matrix.os.sub-command }} build ${{ matrix.os.args }} --release
          cp target/${{ matrix.os.path }}release/js-bindgen-dev${{ matrix.os.exe }} ${{ runner.temp }}/host-tools/
      - name: Upload Host Tools
        uses: actions/upload-artifact@v4
        with:
          name: host-tools-${{ matrix.os.name }}
          path: ${{ runner.temp }}/host-tools/

  build-client:
    name: Build Client - ${{ matrix.target.description }} ${{ matrix.target-feature.description }}

    needs: host-tools

    runs-on: ubuntu-latest

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        target:
          - { name: wasm32, target: wasm32-unknown-unknown, install: true, description: Wasm32 }
          - {
              name: wasm64,
              target: wasm64-unknown-unknown,
              install: false,
              rust: nightly,
              components: -c rust-src,
              description: Wasm64,
            }
        target-feature:
          - { name: default }
          - { name: atomics, rust: nightly, components: -c rust-src, description: Atomics }

    env:
      JBG_DEV_TOOLS: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Stable Rust Override
        run: cp .github/rust-toolchain.toml .
      - name: Install Rust
        run:
          rustup install --no-update --override ${{ matrix.target-feature.components ||
          matrix.target.components }} ${{ matrix.target-feature.rust || matrix.target.rust }}
      - name: Install Target
        if: matrix.target.install
        run: rustup target add ${{ matrix.target.target }}
      - name: Install LLVM
        uses: ZhongRuoyu/setup-llvm@ec41d6e5f3c15c96fa642a49c6e7effac6261778
        with:
          # Rustc v1.95
          llvm-version: 22
      - name: Download Host Tools
        uses: actions/download-artifact@v4
        with:
          name: host-tools-linux
          path: ${{ runner.temp }}/host-tools/
      - name: Install Host Tools
        run: |
          chmod +x ${{ runner.temp }}/host-tools/*
          echo "${{ runner.temp }}/host-tools" >> $GITHUB_PATH
      - name: Enable Caching
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "cache"
          key: ${{ matrix.target.name }}-${{ matrix.target-feature.name }}
          workspaces: client
          cache-bin: false
      - name: Build
        working-directory: host
        run:
          js-bindgen-dev client build -v --targets ${{ matrix.target.name }} --target-features ${{
          matrix.target-feature.name }}

  clippy-client:
    name: Clippy Client - ${{ matrix.target.description }} ${{ matrix.target-feature.description }}

    needs: host-tools

    runs-on: ubuntu-latest

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        target:
          - { name: wasm32, target: wasm32-unknown-unknown, install: true, description: Wasm32 }
          - {
              name: wasm64,
              target: wasm64-unknown-unknown,
              install: false,
              rust: nightly,
              components: -c rust-src,
              description: Wasm64,
            }
        target-feature:
          - { name: default }
          - { name: atomics, rust: nightly, components: -c rust-src, description: Atomics }

    env:
      JBG_DEV_TOOLS: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Stable Rust Override
        run: cp .github/rust-toolchain.toml .
      - name: Install Rust
        run:
          rustup install --no-update --override ${{ matrix.target-feature.components ||
          matrix.target.components }} ${{ matrix.target-feature.rust || matrix.target.rust }}
      - name: Install Target
        if: matrix.target.install
        run: rustup target add ${{ matrix.target.target }}
      - name: Install Clippy
        run: rustup component add clippy
      - name: Install LLVM
        uses: ZhongRuoyu/setup-llvm@ec41d6e5f3c15c96fa642a49c6e7effac6261778
        with:
          # Rustc v1.95
          llvm-version: 22
      - name: Download Host Tools
        uses: actions/download-artifact@v4
        with:
          name: host-tools-linux
          path: ${{ runner.temp }}/host-tools/
      - name: Install Host Tools
        run: |
          chmod +x ${{ runner.temp }}/host-tools/*
          echo "${{ runner.temp }}/host-tools" >> $GITHUB_PATH
      - name: Enable Caching
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "cache"
          key: ${{ matrix.target.name }}-${{ matrix.target-feature.name }}
          workspaces: client
          cache-bin: false
      - name: Clippy
        working-directory: host
        run:
          js-bindgen-dev client check -v --targets ${{ matrix.target.name }} --target-features ${{
          matrix.target-feature.name }}

  test-client:
    name:
      Test Client ${{ matrix.target.description }} ${{ matrix.target-feature.description }} ${{
      matrix.runner.description }}

    needs: host-tools

    runs-on: ${{ matrix.runner.os }}

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        runner:
          - { os: ubuntu-latest, name: linux, runners: all }
          - { os: macos-latest, name: mac-os, runners: safari-driver, description: "- Safari" }
        target:
          - { name: wasm32, target: wasm32-unknown-unknown, install: true, description: Wasm32 }
          - {
              name: wasm64,
              target: wasm64-unknown-unknown,
              install: false,
              rust: nightly,
              components: -c rust-src,
              description: Wasm64,
            }
        target-feature:
          - { name: default }
          - { name: atomics, rust: nightly, components: -c rust-src, description: Atomics }
        exclude:
          - runner: { name: mac-os }
            target: { name: wasm64 }

    env:
      JBG_DEV_TOOLS: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Stable Rust Override
        run: cp .github/rust-toolchain.toml .
      - name: Install Rust
        run:
          rustup install --no-update --override ${{ matrix.target-feature.components ||
          matrix.target.components }} ${{ matrix.target-feature.rust || matrix.target.rust }}
      - name: Install Target
        if: matrix.target.install
        run: rustup target add ${{ matrix.target.target }}
      - name: Install LLVM
        uses: ZhongRuoyu/setup-llvm@ec41d6e5f3c15c96fa642a49c6e7effac6261778
        with:
          # Rustc v1.95
          llvm-version: 22
      - name: Update Node.js
        if: runner.os == 'Linux'
        uses: actions/setup-node@v6
        with:
          node-version: latest
      - name: Install Deno
        if: runner.os == 'Linux'
        uses: denoland/setup-deno@v2
      - name: Download Host Tools
        uses: actions/download-artifact@v4
        with:
          name: host-tools-${{ matrix.runner.name }}
          path: ${{ runner.temp }}/host-tools/
      - name: Install Host Tools
        run: |
          chmod +x ${{ runner.temp }}/host-tools/*
          echo "${{ runner.temp }}/host-tools" >> $GITHUB_PATH
      - name: Enable Caching
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "cache"
          key: ${{ matrix.target.name }}-${{ matrix.target-feature.name }}
          workspaces: client
          cache-bin: false
      - name: Test
        working-directory: host
        run:
          js-bindgen-dev client test -v --targets ${{ matrix.target.name }} --target-features ${{
          matrix.target-feature.name }} --include ${{ matrix.runner.runners }}

  build-host:
    name: Build Host - ${{ matrix.os.description }}

    needs: host-tools

    runs-on: ${{ matrix.os.os }}

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        os:
          - { os: ubuntu-latest, name: linux, description: Linux }
          - { os: macos-latest, name: mac-os, description: macOS }
          - { os: ubuntu-latest, name: windows, real-name: linux, description: Windows }

    env:
      JBG_DEV_TOOLS: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install `cargo-xwin`
        if: matrix.os.name == 'windows'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-xwin
      - name: Restore `cargo-xwin` Cache
        if: matrix.os.name == 'windows'
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/cargo-xwin
          key: cargo-xwin-cache-default
      - name: Download `cargo-xwin` Cache
        if: matrix.os.name == 'windows'
        run: cargo xwin cache xwin
      - name: Save `cargo-xwin` Cache
        if: matrix.os.name == 'windows'
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/cargo-xwin
          key: cargo-xwin-cache-default
      - name: Download Host Tools
        uses: actions/download-artifact@v4
        with:
          name: host-tools-${{ matrix.os.real-name || matrix.os.name }}
          path: ${{ runner.temp }}/host-tools/
      - name: Install Host Tools
        run: |
          chmod +x ${{ runner.temp }}/host-tools/*
          echo "${{ runner.temp }}/host-tools" >> $GITHUB_PATH
      - name: Stable Rust Override
        run: cp .github/rust-toolchain.toml .
      - name: Install Rust
        run: rustup install --no-update
      - name: Enable Caching
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "cache"
          key: ${{ matrix.os.name }}
          workspaces: host
          cache-bin: false
      - name: Build
        working-directory: host
        run: js-bindgen-dev host build -v --targets ${{ matrix.os.name }}

  clippy-host:
    name: Clippy Host - ${{ matrix.os.description }}

    needs: host-tools

    runs-on: ${{ matrix.os.os }}

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        os:
          - { os: ubuntu-latest, name: linux, description: Linux }
          - { os: macos-latest, name: mac-os, description: macOS }
          - { os: ubuntu-latest, name: windows, real-name: linux, description: Windows }

    env:
      JBG_DEV_TOOLS: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install `cargo-xwin`
        if: matrix.os.name == 'windows'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-xwin
      - name: Restore `cargo-xwin` Cache
        if: matrix.os.name == 'windows'
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/cargo-xwin
          key: cargo-xwin-cache-default
      - name: Download `cargo-xwin` Cache
        if: matrix.os.name == 'windows'
        run: cargo xwin cache xwin
      - name: Save `cargo-xwin` Cache
        if: matrix.os.name == 'windows'
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/cargo-xwin
          key: cargo-xwin-cache-default
      - name: Download Host Tools
        uses: actions/download-artifact@v4
        with:
          name: host-tools-${{ matrix.os.real-name || matrix.os.name }}
          path: ${{ runner.temp }}/host-tools/
      - name: Install Host Tools
        run: |
          chmod +x ${{ runner.temp }}/host-tools/*
          echo "${{ runner.temp }}/host-tools" >> $GITHUB_PATH
      - name: Stable Rust Override
        run: cp .github/rust-toolchain.toml .
      - name: Install Rust
        run: rustup install --no-update
      - name: Install Clippy
        run: rustup component add clippy
      - name: Enable Caching
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "cache"
          key: ${{ matrix.os.name }}
          workspaces: host
          cache-bin: false
      - name: Clippy
        working-directory: host
        run: js-bindgen-dev host check -v --targets ${{ matrix.os.name }}

  test-host:
    name: Test Host - ${{ matrix.os.description }}

    needs: host-tools

    runs-on: ${{ matrix.os.os }}

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        os:
          - { os: ubuntu-latest, name: linux, description: Linux }
          - { os: macos-latest, name: mac-os, description: macOS }
          - { os: windows-latest, name: windows, description: Windows }

    env:
      JBG_DEV_TOOLS: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Stable Rust Override
        run: cp .github/rust-toolchain.toml .
      - name: Install Rust
        run: rustup install --no-update
      - name: Install Rust Wasm Target
        run: rustup target add wasm32-unknown-unknown
      - name: Install LLVM
        uses: ZhongRuoyu/setup-llvm@ec41d6e5f3c15c96fa642a49c6e7effac6261778
        with:
          # Rustc v1.95
          llvm-version: 22
      - name: Download Host Tools
        uses: actions/download-artifact@v4
        with:
          name: host-tools-${{ matrix.os.name }}
          path: ${{ runner.temp }}/host-tools/
      - name: Host Tools Permissions
        if: runner.os != 'Windows'
        run: chmod +x ${{ runner.temp }}/host-tools/*
      - name: Install Host Tools
        shell: bash
        run: echo "${{ runner.temp }}/host-tools" >> $GITHUB_PATH
      - name: Enable Caching
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "cache"
          workspaces: host
          cache-bin: false
      - name: Test
        working-directory: host
        run: js-bindgen-dev host test -v

  cargo-js-sys:
    name: Check `cargo-js-sys` - `${{ matrix.package.name }}`

    needs: host-tools

    runs-on: ubuntu-latest

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        package:
          - { name: js-sys, path: client/js-sys }
          - { name: web-sys, path: client/web-sys }

    env:
      JBG_DEV_TOOLS: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Download Host Tools
        uses: actions/download-artifact@v4
        with:
          name: host-tools-linux
          path: ${{ runner.temp }}/host-tools/
      - name: Install Host Tools
        run: |
          chmod +x ${{ runner.temp }}/host-tools/*
          echo "${{ runner.temp }}/host-tools" >> $GITHUB_PATH
      - name: Check
        working-directory: ${{ matrix.package.path }}
        run: cargo-js-sys js-sys -c -v
