name: CodSpeed

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  id-token: write

jobs:
  codspeed:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: host
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: host

      - name: Install cargo-codspeed
        run: cargo install cargo-codspeed --locked

      - name: Build Benchmarks
        run: cargo codspeed build -p js-sys-bindgen --features macro --bench codegen
        env:
          CARGO_CRATE_NAME: test_crate

      - name: Run Benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: cargo codspeed run
          working-directory: host
