name: Lint

on:
  push:
    branches: ["main"]
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  eslint:
    name: ESLint

    runs-on: ubuntu-slim

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        directory:
          - host/ld/src/js
          - host/runner/src/js

    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: NPM Install
        run: npm install --no-audit --no-fund
      - name: Run ESLint
        run: npx eslint

  zizmor:
    name: Zizmor

    runs-on: ubuntu-slim

    timeout-minutes: 20

    permissions:
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Zizmor
        uses: taiki-e/install-action@v2
        with:
          tool: zizmor
      - name: Run Zizmor
        run: zizmor .
