name: Test

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  host:
    name: Test Host ${{ matrix.os.description }}

    runs-on: ${{ matrix.os.os }}

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        os:
          - { os: ubuntu-latest, description: Linux }
          - { os: macos-latest, description: macOS }
          - { os: windows-latest, description: Windows }

    defaults:
      run:
        working-directory: host

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust Wasm Target
        run: rustup target add wasm32-unknown-unknown
      - name: Install LLVM
        uses: ZhongRuoyu/setup-llvm@ec41d6e5f3c15c96fa642a49c6e7effac6261778
        with:
          # Rustc v1.93
          llvm-version: 21
      - name: Run Tests
        run: cargo test --all-features --no-fail-fast

  client:
    name:
      Test Client ${{ matrix.os.description }} ${{ matrix.target.description }} ${{
      matrix.target-feature.description }}

    runs-on: ${{ matrix.os.os }}

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        os:
          - { os: ubuntu-latest, description: Linux }
          - { os: macos-latest, dev: --include safari-driver, description: macOS }
        target:
          - {
              target: wasm32-unknown-unknown,
              install: true,
              rust: stable,
              dev: --target wasm32,
              description: Wasm32,
            }
          - {
              target: wasm64-unknown-unknown,
              install: false,
              rust: nightly,
              components: -c rust-src,
              dev: --target wasm64,
              description: Wasm64,
            }
        target-feature:
          - { dev: --target-feature default }
          - {
              rust: nightly,
              components: -c rust-src,
              dev: --target-feature atomics,
              description: Atomics,
            }
        exclude:
          - os: { description: macOS }
            target: { description: Wasm64 }

    defaults:
      run:
        working-directory: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run:
          rustup install --no-update --profile minimal --override ${{
          matrix.target-feature.components || matrix.target.components }} ${{
          matrix.target-feature.rust || matrix.target.rust }}
      - name: Install Target
        if: matrix.target.install
        run: rustup target add ${{ matrix.target.target }}
      - name: Install LLVM
        uses: ZhongRuoyu/setup-llvm@ec41d6e5f3c15c96fa642a49c6e7effac6261778
        with:
          # Rustc v1.93
          llvm-version: 21
      - name: Update Node.js
        if: runner.os == 'Linux'
        uses: actions/setup-node@v6
        with:
          node-version: latest
      - name: Install Deno
        if: runner.os == 'Linux'
        uses: denoland/setup-deno@v2
      - name: Build Dev Tools
        run: cargo +stable build
      - name: Run
        run:
          cargo +stable run -- test -v ${{ matrix.target.dev }} ${{ matrix.target-feature.dev }} ${{
          matrix.os.dev }}
